///////////////////////////////////////////////////////////
//  AddressInput.java
//  Macromedia ActionScript Implementation of the Class AddressInput
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:03 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:03 PM
 */
public class AddressInput implements Serializable {

	private static final long serialVersionUID = 277424991;
	private int id;
	private int country;
	private String locality;
	private String region;
	private String postOfficeBoxNumber;
	private String postalCode;
	private String streetAddress;

	public int getcountry(){
		return country;
	}

	public int getId(){
		return id;
	}

	public String getlocality(){
		return locality;
	}

	public String getpostalCode(){
		return postalCode;
	}

	public String getpostOfficeBoxNumber(){
		return postOfficeBoxNumber;
	}

	public String getregion(){
		return region;
	}

	public String getstreetAddress(){
		return streetAddress;
	}

	/**
	 * 
	 * @param country
	 */
	public void setcountry(int country){
		this.country = country;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param locality
	 */
	public void setlocality(String locality){
		this.locality = locality;
	}

	/**
	 * 
	 * @param postalcode
	 */
	public void setpostalCode(String postalcode){
		this.postalCode = postalcode;
	}

	/**
	 * 
	 * @param postofficeboxnumber
	 */
	public void setpostOfficeBoxNumber(String postofficeboxnumber){
		this.postOfficeBoxNumber = postofficeboxnumber;
	}

	/**
	 * 
	 * @param region
	 */
	public void setregion(String region){
		this.region = region;
	}

	/**
	 * 
	 * @param streetaddress
	 */
	public void setstreetAddress(String streetaddress){
		this.streetAddress = streetaddress;
	}

}