///////////////////////////////////////////////////////////
//  AssayGeneInput.java
//  Macromedia ActionScript Implementation of the Class AssayGeneInput
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:10:53 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:10:53 AM
 */
@Getter @Setter
public class AssayGeneInput implements Serializable {

	private static final long serialVersionUID = -341134800;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private TraitInput trait;

}