///////////////////////////////////////////////////////////
//  AuditLogsInput.java
//  Macromedia ActionScript Implementation of the Class AuditLogsInput
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:06 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:06 PM
 */
public class AuditLogsInput implements Serializable {

	private static final long serialVersionUID = -63622036;
	private int id;
	private String correlationId;
	private String message;
	InstanceInput instance;

	public String getcorrelationId(){
		return correlationId;
	}

	public int getId(){
		return id;
	}

	public InstanceInput getInstance(){
		return instance;
	}

	public String getmessage(){
		return message;
	}

	/**
	 * 
	 * @param correlationid
	 */
	public void setcorrelationId(String correlationid){
		this.correlationId = correlationid;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param instance
	 */
	public void setInstance(InstanceInput instance){
		this.instance =instance;
	}

	/**
	 * 
	 * @param message
	 */
	public void setmessage(String message){
		this.message = message;
	}

}