///////////////////////////////////////////////////////////
//  CfTypeInput.java
//  Macromedia ActionScript Implementation of the Class CfTypeInput
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:22 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:22 AM
 */
@Getter @Setter
public class CfTypeInput implements Serializable {

	private static final long serialVersionUID = 386730479;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private String help;
	private String type;

}