///////////////////////////////////////////////////////////
//  CollaboratorInput.java
//  Macromedia ActionScript Implementation of the Class CollaboratorInput
//  Generated by Enterprise Architect
//  Created on:      07-Aug-2020 2:59:11 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Aug-2020 2:59:11 PM
 */
public class CollaboratorInput implements Serializable {

	private static final long serialVersionUID = -451861013;
	private int id;
	private int tenant;
	private String affiliation;
	private String contactPoint;
	private String identifier;
	PersonInput person;

	public String getaffiliation(){
		return affiliation;
	}

	public String getcontactPoint(){
		return contactPoint;
	}

	public int getId(){
		return id;
	}

	public String getidentifier(){
		return identifier;
	}

	public PersonInput getperson(){
		return person;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param affiliation
	 */
	public void setaffiliation(String affiliation){
		this.affiliation = affiliation;
	}

	/**
	 * 
	 * @param contactpoint
	 */
	public void setcontactPoint(String contactpoint){
		this.contactPoint = contactpoint;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param identifier
	 */
	public void setidentifier(String identifier){
		this.identifier = identifier;
	}

	/**
	 * 
	 * @param person
	 */
	public void setperson(PersonInput person){
		this.person =person;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

}