///////////////////////////////////////////////////////////
//  ComponentInput.java
//  Macromedia ActionScript Implementation of the Class ComponentInput
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 12:06:56 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import org.ebs.model.InstanceModel;
import org.ebs.model.MessageModel;
import org.ebs.model.ModuleModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 12:06:56 AM
 */
public class ComponentInput implements Serializable {

	private static final long serialVersionUID = -181086647;
	private int id;
	private String name;
	private String version;
	private String releaseNo;
	private String info;

	public int getId(){
		return id;
	}

	public String getinfo(){
		return info;
	}

	public String getname(){
		return name;
	}

	public String getreleaseNo(){
		return releaseNo;
	}

	public String getversion(){
		return version;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param info
	 */
	public void setinfo(String info){
		this.info = info;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param releaseno
	 */
	public void setreleaseNo(String releaseno){
		this.releaseNo = releaseno;
	}

	/**
	 * 
	 * @param version
	 */
	public void setversion(String version){
		this.version = version;
	}

}