///////////////////////////////////////////////////////////
//  CountryInput.java
//  Macromedia ActionScript Implementation of the Class CountryInput
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:26 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:26 PM
 */
public class CountryInput implements Serializable {

	private static final long serialVersionUID = -209196690;
	private int id;
	private String name;
	private String iso3;
	private int number;
	private String full_name;
	private String code;

	public String getcode(){
		return code;
	}

	public String getfull_name(){
		return full_name;
	}

	public int getId(){
		return id;
	}

	public String getiso3(){
		return iso3;
	}

	public String getname(){
		return name;
	}

	public int getnumber(){
		return number;
	}

	/**
	 * 
	 * @param code
	 */
	public void setcode(String code){
		this.code = code;
	}

	/**
	 * 
	 * @param full_name
	 */
	public void setfull_name(String full_name){
		this.full_name = full_name;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param iso3
	 */
	public void setiso3(String iso3){
		this.iso3 = iso3;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param number
	 */
	public void setnumber(int number){
		this.number = number;
	}

}