///////////////////////////////////////////////////////////
//  EmailTemplateInput.java
//  Macromedia ActionScript Implementation of the Class EmailTemplateInput
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:27 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:27 AM
 */
@Getter @Setter
public class EmailTemplateInput implements Serializable {

	private static final long serialVersionUID = 130220758;
	private int id;
	private String name;
	private String subject;
	private String template;
	private TenantInput tenant;
	private PersonInput person;

}