///////////////////////////////////////////////////////////
//  EmailTemplateInput.java
//  Macromedia ActionScript Implementation of the Class EmailTemplateInput
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:11:13 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:11:13 AM
 */
@Getter @Setter
public class EmailTemplateInput implements Serializable {

	private static final long serialVersionUID = 210172452;
	private int id;
	private String name;
	private String subject;
	private String template;
	private TenantInput tenant;

}