///////////////////////////////////////////////////////////
//  ModuleInput.java
//  Macromedia ActionScript Implementation of the Class ModuleInput
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:13:46 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:13:46 PM
 */
public class ModuleInput implements Serializable {

	private static final long serialVersionUID = -519214078;
	private int id;
	private String name;
	private String description;
	private String help;
	private String route;
	Set<WorkflowNodeInput> workflownode;
	ComponentInput component;

	public ComponentInput getComponent(){
		return component;
	}

	public String getdescription(){
		return description;
	}

	public String gethelp(){
		return help;
	}

	public int getId(){
		return id;
	}

	public String getname(){
		return name;
	}

	public String getroute(){
		return route;
	}

	public Set<WorkflowNodeInput> getWorkflowNode(){
		return workflownode;
	}

	/**
	 * 
	 * @param component
	 */
	public void setComponent(ComponentInput component){
		this.component =component;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param help
	 */
	public void sethelp(String help){
		this.help = help;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param route
	 */
	public void setroute(String route){
		this.route = route;
	}

	/**
	 * 
	 * @param workflownode
	 */
	public void setWorkflowNode(Set<WorkflowNodeInput> workflownode){
		this.workflownode =workflownode;
	}

}