///////////////////////////////////////////////////////////
//  OrganizationInput.java
//  Macromedia ActionScript Implementation of the Class OrganizationInput
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:44:06 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:44:06 PM
 */
@Getter @Setter
public class OrganizationInput implements Serializable {

	private static final long serialVersionUID = 277602373;
	private int id;
	private String legalName;
	private String phone;
	private String webpage;
	private String slogan;
	private String name;
	private String taxID;
	private String logo;
	private String isActive;
	private int defaultAuthentication;
	private int defaultTheme;
	private String organizationcode;
	private CustomerInput customer;

}