///////////////////////////////////////////////////////////
//  PartnerInput.java
//  Macromedia ActionScript Implementation of the Class PartnerInput
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:21 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:21 PM
 */
public class PartnerInput implements Serializable {

	private static final long serialVersionUID = 390568513;
	private int id;
	private String affiliation;
	private String contactPoint;
	private String indentifier;
	PearsonInput pearson;

	public String getaffiliation(){
		return affiliation;
	}

	public String getcontactPoint(){
		return contactPoint;
	}

	public int getId(){
		return id;
	}

	public String getindentifier(){
		return indentifier;
	}

	public PearsonInput getPearson(){
		return pearson;
	}

	/**
	 * 
	 * @param affiliation
	 */
	public void setaffiliation(String affiliation){
		this.affiliation = affiliation;
	}

	/**
	 * 
	 * @param contactpoint
	 */
	public void setcontactPoint(String contactpoint){
		this.contactPoint = contactpoint;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param indentifier
	 */
	public void setindentifier(String indentifier){
		this.indentifier = indentifier;
	}

	/**
	 * 
	 * @param pearson
	 */
	public void setPearson(PearsonInput pearson){
		this.pearson =pearson;
	}

}