///////////////////////////////////////////////////////////
//  PurposeInput.java
//  Macromedia ActionScript Implementation of the Class PurposeInput
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:14:07 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:14:07 PM
 */
public class PurposeInput implements Serializable {

	private static final long serialVersionUID = -4636337;
	private int id;
	private int tenant;
	private String name;
	private String code;
	private String description;

	public String getcode(){
		return code;
	}

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public String getname(){
		return name;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param code
	 */
	public void setcode(String code){
		this.code = code;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

}