///////////////////////////////////////////////////////////
//  RequestInput.java
//  Macromedia ActionScript Implementation of the Class RequestInput
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:05:51 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:05:51 AM
 */
@Getter @Setter
public class RequestInput implements Serializable {

	private static final long serialVersionUID = -408363912;
	private int id;
	private int tenant;
	private String requester;
	private String requestcode;
	private Date submitiondate;
	private String admincontact;
	private String chargeaccount;
	private String description;
 
	private WorkflowInstanceInput workflowinstance;
	private PersonInput person;

}