///////////////////////////////////////////////////////////
//  SeasonInput.java
//  Macromedia ActionScript Implementation of the Class SeasonInput
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:05:57 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:05:57 AM
 */
@Getter @Setter
public class SeasonInput implements Serializable {

	private static final long serialVersionUID = -12715604;
	private int id;
	private int tenant;
	private String seasoncode;
	private String seasonname;
	private String description;
	private Set<CropInput> crops;

}