///////////////////////////////////////////////////////////
//  ServiceInput.java
//  Macromedia ActionScript Implementation of the Class ServiceInput
//  Generated by Enterprise Architect
//  Created on:      07-Aug-2020 3:01:24 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Aug-2020 3:01:24 PM
 */
public class ServiceInput implements Serializable {

	private static final long serialVersionUID = -279947866;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private String code;
	PurposeInput purpose;

	public String getcode(){
		return code;
	}

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public String getname(){
		return name;
	}

	public PurposeInput getpurpose(){
		return purpose;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param code
	 */
	public void setcode(String code){
		this.code = code;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param purpose
	 */
	public void setpurpose(PurposeInput purpose){
		this.purpose =purpose;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

}