///////////////////////////////////////////////////////////
//  SessionInput.java
//  Macromedia ActionScript Implementation of the Class SessionInput
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:06:07 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;

import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:06:07 AM
 */
@Getter @Setter
public class SessionInput implements Serializable {

	private static final long serialVersionUID = 405238973;
	private int id;
	private int tenant;
	private String websession;
	private String remoteaddress;
	private String remotehost;
	private UserInput user;
	private InstanceInput instance;

}