///////////////////////////////////////////////////////////
//  StyleThemeInput.java
//  Macromedia ActionScript Implementation of the Class StyleThemeInput
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:57 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:57 AM
 */
@Getter @Setter
public class StyleThemeInput implements Serializable {

	private static final long serialVersionUID = 245396730;
	private int id;
	private int tenant;
	private String description;
	private String path;
	private String physicalName;
	private Boolean defaulta;

}