///////////////////////////////////////////////////////////
//  TraitClassInput.java
//  Macromedia ActionScript Implementation of the Class TraitClassInput
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:21 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:21 AM
 */
@Getter @Setter
public class TraitClassInput implements Serializable {

	private static final long serialVersionUID = 33576928;
	private int id;
	private int tenant;
	private String name;
	private String description;

}