///////////////////////////////////////////////////////////
//  VendorInput.java
//  Macromedia ActionScript Implementation of the Class VendorInput
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:44:57 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:44:57 PM
 */
@Getter @Setter
public class VendorInput implements Serializable {

	private static final long serialVersionUID = -287263872;
	private int id;
	private int tenant;
	private String code;
	private String reference;
	private String status;
	private DataFormatInput dataformat;
	private Set<ServiceInput> services;
	private TechnologyPlatformInput technologyplatform;
	private PersonInput person;

}