///////////////////////////////////////////////////////////
//  VendorInput.java
//  Macromedia ActionScript Implementation of the Class VendorInput
//  Generated by Enterprise Architect
//  Created on:      13-Jul-2020 5:07:33 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Jul-2020 5:07:33 PM
 */
public class VendorInput implements Serializable {

	private static final long serialVersionUID = -123273023;
	private int id;
	private int tenant;
	private String code;
	private String reference;
	private String status;
	CountryInput country;
	PersonInput person;

	public String getcode(){
		return code;
	}

	public CountryInput getcountry(){
		return country;
	}

	public int getId(){
		return id;
	}

	public PersonInput getperson(){
		return person;
	}

	public String getreference(){
		return reference;
	}

	public String getstatus(){
		return status;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param code
	 */
	public void setcode(String code){
		this.code = code;
	}

	/**
	 * 
	 * @param country
	 */
	public void setcountry(CountryInput country){
		this.country =country;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param person
	 */
	public void setperson(PersonInput person){
		this.person =person;
	}

	/**
	 * 
	 * @param reference
	 */
	public void setreference(String reference){
		this.reference = reference;
	}

	/**
	 * 
	 * @param status
	 */
	public void setstatus(String status){
		this.status = status;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

}