///////////////////////////////////////////////////////////
//  VendorInput.java
//  Macromedia ActionScript Implementation of the Class VendorInput
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:14:48 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:14:48 PM
 */
public class VendorInput implements Serializable {

	private static final long serialVersionUID = 55873686;
	private int id;
	private int tenant;
	private String code;
	private String reference;
	private String status;
	DataFormatInput dataformat;
	Set<ServiceInput> service;
	CountryInput country;
	PersonInput person;

	public String getcode(){
		return code;
	}

	public CountryInput getCountry(){
		return country;
	}

	public DataFormatInput getDataFormat(){
		return dataformat;
	}

	public int getId(){
		return id;
	}

	public PersonInput getPerson(){
		return person;
	}

	public String getreference(){
		return reference;
	}

	public Set<ServiceInput> getService(){
		return service;
	}

	public String getstatus(){
		return status;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param code
	 */
	public void setcode(String code){
		this.code = code;
	}

	/**
	 * 
	 * @param country
	 */
	public void setCountry(CountryInput country){
		this.country =country;
	}

	/**
	 * 
	 * @param dataformat
	 */
	public void setDataFormat(DataFormatInput dataformat){
		this.dataformat =dataformat;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param person
	 */
	public void setPerson(PersonInput person){
		this.person =person;
	}

	/**
	 * 
	 * @param reference
	 */
	public void setreference(String reference){
		this.reference = reference;
	}

	/**
	 * 
	 * @param service
	 */
	public void setService(Set<ServiceInput> service){
		this.service =service;
	}

	/**
	 * 
	 * @param status
	 */
	public void setstatus(String status){
		this.status = status;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

}