///////////////////////////////////////////////////////////
//  WorkflowCFValueInput.java
//  Macromedia ActionScript Implementation of the Class WorkflowCFValueInput
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:45:01 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:45:01 PM
 */
@Getter @Setter
public class WorkflowCFValueInput implements Serializable {

	private static final long serialVersionUID = -516804333;
	private int id;
	private int tenant;
	private boolean flagvalue;
	private String textvalue;
	private int numvalue;
	private Date datevalue;
	private int codevalue;
	private RequestInput request;
	private WorkflowNodeCFInput workflownodecf;

}