///////////////////////////////////////////////////////////
//  WorkflowNodeInput.java
//  Macromedia ActionScript Implementation of the Class WorkflowNodeInput
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 12:20:51 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 12:20:51 AM
 */
@Getter @Setter
public class WorkflowNodeInput implements Serializable {

	private static final long serialVersionUID = 64853136;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private String help;
	private int sequence;
	private boolean requireapproval;
	private WorkflowInput workflow;
	private EntityReferenceInput entityreference;
	private HtmlTagInput htmltag;
	private ProcessInput process;
	private ModuleInput module;

}