///////////////////////////////////////////////////////////
//  WorkflowStatusInput.java
//  Macromedia ActionScript Implementation of the Class WorkflowStatusInput
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:45:18 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:45:18 PM
 */
@Getter @Setter
public class WorkflowStatusInput implements Serializable {

	private static final long serialVersionUID = 303805431;
	private int id;
	private int tenant;
	private Date initiatedate;
	private Date completiondate;
	private WorkflowStatusTypeInput workflowstatustype;
	private WorkflowInstanceInput workflowinstance;

}