///////////////////////////////////////////////////////////
//  WorkflowCFTypeInput.java
//  Macromedia ActionScript Implementation of the Class WorkflowCFTypeInput
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:06:28 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to.Input;

import java.io.Serializable;

import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:06:28 AM
 */
@Getter @Setter
public class WorkflowCFTypeInput implements Serializable {

	private static final long serialVersionUID = 195433512;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private String help;
	private String type;

}