///////////////////////////////////////////////////////////
//  AlertService.java
//  Macromedia ActionScript Implementation of the Interface AlertService
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:20 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.AlertTo;
import org.ebs.services.to.Input.AlertInput;
import org.ebs.services.to.AlertRuleTo;
import org.ebs.services.to.HtmlTagTo;
import org.ebs.services.to.PreferenceTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:20 AM
 */
public interface AlertService {

	/**
	 * 
	 * @param Alert
	 */
	public AlertTo createAlert(AlertInput Alert);

	/**
	 * 
	 * @param alertId
	 */
	public int deleteAlert(int alertId);

	/**
	 * 
	 * @param alertId
	 */
	public Optional<AlertTo> findAlert(int alertId);

	/**
	 * 
	 * @param alertId
	 */
	public Set<AlertRuleTo> findAlertRules(int alertId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<AlertTo> findAlerts(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param alertId
	 */
	public Optional<HtmlTagTo> findHtmlTag(int alertId);

	/**
	 * 
	 * @param alertId
	 */
	public Set<PreferenceTo> findPreferences(int alertId);

	/**
	 * 
	 * @param alert
	 */
	public AlertTo modifyAlert(AlertInput alert);

}