///////////////////////////////////////////////////////////
//  AssayGeneService.java
//  Macromedia ActionScript Implementation of the Interface AssayGeneService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:17 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.AssayGeneRepository;
import org.ebs.services.to.AssayGeneTo;
import org.ebs.services.to.Input.AssayGeneInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:17 PM
 */
public interface AssayGeneService {

	/**
	 * 
	 * @param AssayGene
	 */
	public AssayGeneTo createAssayGene(AssayGeneInput AssayGene);

	/**
	 * 
	 * @param idassaygene
	 */
	public int deleteAssayGene(int idassaygene);

	/**
	 * 
	 * @param assaygeneId
	 */
	public Optional<AssayGeneTo> findAssayGene(int assaygeneId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<AssayGeneTo> findAssayGenes(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param assaygene
	 */
	public AssayGeneTo modifyAssayGene(AssayGeneInput assaygene);

}