///////////////////////////////////////////////////////////
//  AuditLogsService.java
//  Macromedia ActionScript Implementation of the Interface AuditLogsService
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:06 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.AuditLogsRepository;
import org.ebs.services.to.AuditLogsTo;
import org.ebs.services.to.Input.AuditLogsInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:06 PM
 */
public interface AuditLogsService {

	/**
	 * 
	 * @param AuditLogs
	 */
	public AuditLogsTo createAuditLogs(AuditLogsInput AuditLogs);

	/**
	 * 
	 * @param idauditlogs
	 */
	public int deleteAuditLogs(int idauditlogs);

	/**
	 * 
	 * @param auditlogsId
	 */
	public Optional<AuditLogsTo> findAuditLogs(int auditlogsId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<AuditLogsTo> findAuditLogss(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param auditlogs
	 */
	public AuditLogsTo modifyAuditLogs(AuditLogsInput auditlogs);

}