///////////////////////////////////////////////////////////
//  AuthenticationTypeService.java
//  Macromedia ActionScript Implementation of the Interface AuthenticationTypeService
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:10:59 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.AuthenticationTypeTo;
import org.ebs.services.to.Input.AuthenticationTypeInput;
import org.ebs.services.to.TenantTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:10:59 AM
 */
public interface AuthenticationTypeService {

	/**
	 * 
	 * @param AuthenticationType
	 */
	public AuthenticationTypeTo createAuthenticationType(AuthenticationTypeInput AuthenticationType);

	/**
	 * 
	 * @param authenticationTypeId
	 */
	public int deleteAuthenticationType(int authenticationTypeId);

	/**
	 * 
	 * @param authenticationTypeId
	 */
	public Optional<AuthenticationTypeTo> findAuthenticationType(int authenticationTypeId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<AuthenticationTypeTo> findAuthenticationTypes(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param authenticationTypeId
	 */
	public Set<TenantTo> findTenants(int authenticationTypeId);

	/**
	 * 
	 * @param authenticationType
	 */
	public AuthenticationTypeTo modifyAuthenticationType(AuthenticationTypeInput authenticationType);

}