///////////////////////////////////////////////////////////
//  DataFormatService.java
//  Macromedia ActionScript Implementation of the Interface DataFormatService
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 12:19:09 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.DataFormatTo;
import org.ebs.services.to.Input.DataFormatInput;
import org.ebs.services.to.VendorTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 12:19:09 AM
 */
public interface DataFormatService {

	/**
	 * 
	 * @param DataFormat
	 */
	public DataFormatTo createDataFormat(DataFormatInput DataFormat);

	/**
	 * 
	 * @param dataFormatId
	 */
	public int deleteDataFormat(int dataFormatId);

	/**
	 * 
	 * @param dataFormatId
	 */
	public Optional<DataFormatTo> findDataFormat(int dataFormatId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<DataFormatTo> findDataFormats(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param dataformatId
	 */
	public Set<VendorTo> findVendors(int dataformatId);

	/**
	 * 
	 * @param dataFormat
	 */
	public DataFormatTo modifyDataFormat(DataFormatInput dataFormat);

}