///////////////////////////////////////////////////////////
//  EntityReferenceService.java
//  Macromedia ActionScript Implementation of the Interface EntityReferenceService
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:11:16 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.EntityReferenceTo;
import org.ebs.services.to.Input.EntityReferenceInput;
import org.ebs.services.to.AttributesTo;
import org.ebs.services.to.EmailTemplateTo;
import org.ebs.services.to.WorkflowTo;
import org.ebs.services.to.SegmentTo;
import org.ebs.services.to.WorkflowNodeTo;
import org.ebs.services.to.NumberSequenceRuleTo;
import org.ebs.services.to.WorkflowNodeCFTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:11:16 AM
 */
public interface EntityReferenceService {

	/**
	 * 
	 * @param EntityReference
	 */
	public EntityReferenceTo createEntityReference(EntityReferenceInput EntityReference);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public int deleteEntityReference(int entityReferenceId);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Set<AttributesTo> findAttributess(int entityReferenceId);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Set<EmailTemplateTo> findEmailTemplates(int entityReferenceId);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Optional<EntityReferenceTo> findEntityReference(int entityReferenceId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<EntityReferenceTo> findEntityReferences(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Set<NumberSequenceRuleTo> findNumberSequenceRules(int entityReferenceId);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Set<SegmentTo> findSegments(int entityReferenceId);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Set<WorkflowNodeCFTo> findWorkflowNodeCFs(int entityReferenceId);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Set<WorkflowNodeTo> findWorkflowNodes(int entityReferenceId);

	/**
	 * 
	 * @param entityReferenceId
	 */
	public Set<WorkflowTo> findWorkflows(int entityReferenceId);

	/**
	 * 
	 * @param entityReference
	 */
	public EntityReferenceTo modifyEntityReference(EntityReferenceInput entityReference);

}