///////////////////////////////////////////////////////////
//  EntityReferenceServiceImpl.java
//  Macromedia ActionScript Implementation of the Class EntityReferenceServiceImpl
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:05:07 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import org.ebs.model.repos.EntityReferenceRepository;
import org.ebs.model.repos.AttributesRepository;
import org.ebs.model.repos.EmailTemplateRepository;
import org.ebs.model.repos.WorkflowRepository;
import org.ebs.model.repos.SegmentRepository;
import org.ebs.model.repos.WorkflowNodeRepository;
import org.ebs.model.repos.NumberSequenceRuleRepository;
import org.ebs.model.repos.WorkflowNodeCFRepository;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.Page;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;
import org.ebs.services.to.EntityReferenceTo;
import org.ebs.services.to.Input.EntityReferenceInput;
import org.ebs.model.EntityReferenceModel;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.ebs.util.Utils;
import org.springframework.core.convert.ConversionService;
import java.util.stream.Collectors;
import java.util.Set;
import org.ebs.services.to.WorkflowNodeCFTo;
import org.ebs.services.to.AttributesTo;
import org.ebs.services.to.EmailTemplateTo;
import org.ebs.services.to.WorkflowTo;
import org.ebs.services.to.SegmentTo;
import org.ebs.services.to.WorkflowNodeTo;
import org.ebs.services.to.NumberSequenceRuleTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:05:07 AM
 */
@Service @Transactional(readOnly = true)
  class EntityReferenceServiceImpl implements EntityReferenceService {

	private EntityReferenceRepository entityreferenceRepository;
	private ConversionService converter;
	public AttributesRepository attributesRepository;
	public EmailTemplateRepository emailtemplateRepository;
	public WorkflowRepository workflowRepository;
	public SegmentRepository segmentRepository;
	public WorkflowNodeRepository workflownodeRepository;
	public NumberSequenceRuleRepository numbersequenceruleRepository;
	public WorkflowNodeCFRepository workflownodecfRepository;

	/**
	 *
	 * @param EntityReference
	 */
	@Override @Transactional(readOnly = false)
	public EntityReferenceTo createentityreference(EntityReferenceInput EntityReference){
		EntityReferenceModel model = converter.convert(EntityReference,EntityReferenceModel.class);
		 model.setId(0);

		 model= entityreferenceRepository.save(model);
		 return converter.convert(model, EntityReferenceTo.class);
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	@Override @Transactional(readOnly = false)
	public int deleteentityreference(int entityreferenceId){
		EntityReferenceModel entityreference = entityreferenceRepository.findById(entityreferenceId).orElseThrow(() -> new RuntimeException("EntityReference not found"));
		 entityreference.setDeleted(true);
		  entityreferenceRepository.save(entityreference);
		 return entityreferenceId;
	}

	/**
	 *
	 * @param workflownodecfRepository
	 * @param entityreferenceRepository
	 * @param converter
	 * @param attributesRepository
	 * @param emailtemplateRepository
	 * @param workflowRepository
	 * @param segmentRepository
	 * @param workflownodeRepository
	 * @param numbersequenceruleRepository
	 */
	@Autowired
	public EntityReferenceServiceImpl(WorkflowNodeCFRepository workflownodecfRepository, EntityReferenceRepository entityreferenceRepository, ConversionService converter, AttributesRepository attributesRepository, EmailTemplateRepository emailtemplateRepository, WorkflowRepository workflowRepository, SegmentRepository segmentRepository, WorkflowNodeRepository workflownodeRepository, NumberSequenceRuleRepository numbersequenceruleRepository){
		this.entityreferenceRepository =entityreferenceRepository;
		 this.converter = converter;
		 this.attributesRepository = attributesRepository;
		 this.emailtemplateRepository = emailtemplateRepository;
		 this.workflowRepository = workflowRepository;
		 this.segmentRepository = segmentRepository;
		 this.workflownodeRepository = workflownodeRepository;
		 this.numbersequenceruleRepository = numbersequenceruleRepository;
		 this.workflownodecfRepository = workflownodecfRepository;
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	public Set<AttributesTo> findattributess(int entityreferenceId){
		return attributesRepository.findByEntityreferenceId(entityreferenceId).stream().map(e -> converter.convert(e,AttributesTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	public Set<EmailTemplateTo> findemailtemplates(int entityreferenceId){
		return entityreferenceRepository.findById(entityreferenceId).get().getEmailtemplates().stream().map(e->converter.convert(e, EmailTemplateTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	@Override
	public Optional<EntityReferenceTo> findentityreference(int entityreferenceId){
		if(entityreferenceId <1)
		 {return Optional.empty();}
		 return entityreferenceRepository.findById(entityreferenceId).filter(r -> !r.getDeleted().booleanValue()).map(r -> converter.convert(r,EntityReferenceTo.class));
	}

	/**
	 *
	 * @param page
	 * @param sort
	 * @param filters
	 */
	@Override
	public Page<EntityReferenceTo> findentityreferences(PageInput page, SortInput sort, List<FilterInput> filters, boolean disjunctionFilters){
		return entityreferenceRepository.findByCriteria(EntityReferenceModel.class,filters,sort,page,disjunctionFilters).map(r -> converter.convert(r,EntityReferenceTo.class));
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	public Set<NumberSequenceRuleTo> findnumbersequencerules(int entityreferenceId){
		return entityreferenceRepository.findById(entityreferenceId).get().getNumbersequencerules().stream().map(e->converter.convert(e, NumberSequenceRuleTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	public Set<SegmentTo> findsegments(int entityreferenceId){
		return segmentRepository.findByEntityreferenceId(entityreferenceId).stream().map(e -> converter.convert(e,SegmentTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	public Set<WorkflowNodeCFTo> findworkflownodecfs(int entityreferenceId){
		return workflownodecfRepository.findByEntityreferenceId(entityreferenceId).stream().map(e -> converter.convert(e,WorkflowNodeCFTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	public Set<WorkflowNodeTo> findworkflownodes(int entityreferenceId){
		return workflownodeRepository.findByEntityreferenceId(entityreferenceId).stream().map(e -> converter.convert(e,WorkflowNodeTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param entityreferenceId
	 */
	public Set<WorkflowTo> findworkflows(int entityreferenceId){
		return workflowRepository.findByEntityreferenceId(entityreferenceId).stream().map(e -> converter.convert(e,WorkflowTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param entityreference
	 */
	@Override @Transactional(readOnly = false)
	public EntityReferenceTo modifyentityreference(EntityReferenceInput entityreference){
		EntityReferenceModel target= entityreferenceRepository.findById(entityreference.getId()).orElseThrow(() -> new RuntimeException("EntityReference not found"));
		 EntityReferenceModel source= converter.convert(entityreference,EntityReferenceModel.class);
		 Utils.copyNotNulls(source,target);
		 return converter.convert(entityreferenceRepository.save(target), EntityReferenceTo.class);
	}

}