///////////////////////////////////////////////////////////
//  LanguageService.java
//  Macromedia ActionScript Implementation of the Interface LanguageService
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:16 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.LanguageRepository;
import org.ebs.services.to.LanguageTo;
import org.ebs.services.to.Input.LanguageInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:16 PM
 */
public interface LanguageService {

	/**
	 * 
	 * @param Language
	 */
	public LanguageTo createLanguage(LanguageInput Language);

	/**
	 * 
	 * @param idlanguage
	 */
	public int deleteLanguage(int idlanguage);

	/**
	 * 
	 * @param languageId
	 */
	public Optional<LanguageTo> findLanguage(int languageId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<LanguageTo> findLanguages(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param language
	 */
	public LanguageTo modifyLanguage(LanguageInput language);

}