///////////////////////////////////////////////////////////
//  ModuleService.java
//  Macromedia ActionScript Implementation of the Interface ModuleService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:44 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.ModuleRepository;
import org.springframework.stereotype.Component;
import org.ebs.services.to.ModuleTo;
import org.ebs.services.to.Input.ModuleInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:45 PM
 */
public interface ModuleService {

	/**
	 * 
	 * @param Module
	 */
	public ModuleTo createModule(ModuleInput Module);

	/**
	 * 
	 * @param idmodule
	 */
	public int deleteModule(int idmodule);

	/**
	 * 
	 * @param moduleId
	 */
	public Optional<ModuleTo> findModule(int moduleId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<ModuleTo> findModules(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param module
	 */
	public ModuleTo modifyModule(ModuleInput module);

}