///////////////////////////////////////////////////////////
//  PermissionService.java
//  Macromedia ActionScript Implementation of the Interface PermissionService
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:43:02 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.services.to.PermissionTo;
import org.ebs.services.to.Input.PermissionInput;
import org.ebs.services.to.RoleActionTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:43:02 AM
 */
public interface PermissionService {

	/**
	 * 
	 * @param Permission
	 */
	public PermissionTo createPermission(PermissionInput Permission);

	/**
	 * 
	 * @param permissionId
	 */
	public int deletePermission(int permissionId);

	/**
	 * 
	 * @param permissionId
	 */
	public Optional<PermissionTo> findPermission(int permissionId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<PermissionTo> findPermissions(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param permissionId
	 */
	public Optional<RoleActionTo> findRoleAction(int permissionId);

	/**
	 * 
	 * @param permission
	 */
	public PermissionTo modifyPermission(PermissionInput permission);

}