///////////////////////////////////////////////////////////
//  PersonService.java
//  Macromedia ActionScript Implementation of the Interface PersonService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:53 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.PersonRepository;
import org.ebs.services.to.Input.PersonInput;
import org.ebs.services.to.PersonTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:53 PM
 */
public interface PersonService {

	/**
	 * 
	 * @param Person
	 */
	public PersonTo createPerson(PersonInput Person);

	/**
	 * 
	 * @param idperson
	 */
	public int deletePerson(int idperson);

	/**
	 * 
	 * @param personId
	 */
	public Optional<PersonTo> findPerson(int personId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<PersonTo> findPersons(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param person
	 */
	public PersonTo modifyPerson(PersonInput person);

}