///////////////////////////////////////////////////////////
//  ProcessService.java
//  Macromedia ActionScript Implementation of the Interface ProcessService
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:19:57 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.services.to.ProcessTo;
import org.ebs.services.to.Input.ProcessInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:19:57 AM
 */
public interface ProcessService {

	/**
	 * 
	 * @param Process
	 */
	public ProcessTo createProcess(ProcessInput Process);

	/**
	 * 
	 * @param processId
	 */
	public int deleteProcess(int processId);

	/**
	 * 
	 * @param processId
	 */
	public Optional<ProcessTo> findProcess(int processId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<ProcessTo> findProcesss(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param process
	 */
	public ProcessTo modifyProcess(ProcessInput process);

}