///////////////////////////////////////////////////////////
//  ProjectService.java
//  Macromedia ActionScript Implementation of the Interface ProjectService
//  Generated by Enterprise Architect
//  Created on:      13-Jul-2020 5:07:06 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.services.to.ProjectTo;
import org.ebs.services.to.Input.ProjectInput;
import org.ebs.services.to.ProgramTo;
import org.ebs.services.to.PersonTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Jul-2020 5:07:06 PM
 */
public interface ProjectService {

	/**
	 * 
	 * @param Project
	 */
	public ProjectTo createProject(ProjectInput Project);

	/**
	 * 
	 * @param projectId
	 */
	public int deleteProject(int projectId);

	/**
	 * 
	 * @param projectId
	 */
	public Optional<PersonTo> findPerson(int projectId);

	/**
	 * 
	 * @param projectId
	 */
	public Optional<ProgramTo> findProgram(int projectId);

	/**
	 * 
	 * @param projectId
	 */
	public Optional<ProjectTo> findProject(int projectId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<ProjectTo> findProjects(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param project
	 */
	public ProjectTo modifyProject(ProjectInput project);

}