///////////////////////////////////////////////////////////
//  ProjectService.java
//  Macromedia ActionScript Implementation of the Interface ProjectService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:03 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.ProjectRepository;
import org.ebs.services.to.ProjectTo;
import org.ebs.services.to.Input.ProjectInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:03 PM
 */
public interface ProjectService {

	/**
	 * 
	 * @param Project
	 */
	public ProjectTo createProject(ProjectInput Project);

	/**
	 * 
	 * @param idproject
	 */
	public int deleteProject(int idproject);

	/**
	 * 
	 * @param projectId
	 */
	public Optional<ProjectTo> findProject(int projectId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<ProjectTo> findProjects(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param project
	 */
	public ProjectTo modifyProject(ProjectInput project);

}