///////////////////////////////////////////////////////////
//  PurposeImpl.java
//  Macromedia ActionScript Implementation of the Class PurposeImpl
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:04 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;

import org.ebs.model.PurposeModel;
import org.ebs.model.repos.PurposeRepository;
import org.ebs.services.to.PurposeTo;
import org.ebs.services.to.Input.PurposeInput;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.ebs.util.Utils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.ConversionService;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:04 PM
 */
@Service @Transactional(readOnly = true)
public class PurposeImpl implements PurposeService {

	private PurposeRepository purposeRepository;
	@Autowired
	private ConversionService converter;

	/**
	 * 
	 * @param Purpose
	 */
	@Override @Transactional(readOnly = false)
	public PurposeTo createPurpose(PurposeInput Purpose){
		PurposeModel model = converter.convert(Purpose,PurposeModel.class); 
		 model.setId(0);
		  
		 model= purposeRepository.save(model); 
		 return converter.convert(model, PurposeTo.class); 
	}

	/**
	 * 
	 * @param idpurpose
	 */
	@Override @Transactional(readOnly = false)
	public int deletePurpose(int idpurpose){
		PurposeModel purpose = purposeRepository.findById(idpurpose).orElseThrow(() -> new RuntimeException("Request not found")); 
		 purpose.setDeleted(true); 
		  purposeRepository.save(purpose); 
		 return idpurpose;
	}

	/**
	 * 
	 * @param purposeId
	 */
	@Override
	public Optional<PurposeTo> findPurpose(int purposeId){
		if(purposeId <1) 
		 {return Optional.empty();} 
		 return purposeRepository.findById(purposeId).filter(r -> !r.getDeleted().booleanValue()).map(r -> converter.convert(r,PurposeTo.class));
	}

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	@Override
	public Page<PurposeTo> findPurposes(PageInput page, SortInput sort, List<FilterInput> filters){
		return purposeRepository.findByCriteria(PurposeModel.class,filters,sort,page).map(r -> converter.convert(r,PurposeTo.class));
	}

	/**
	 * 
	 * @param purpose
	 */
	@Override @Transactional(readOnly = false)
	public PurposeTo modifyPurpose(PurposeInput purpose){
		PurposeModel target= purposeRepository.findById(purpose.getId()).orElseThrow(() -> new RuntimeException("Request not found")); 
		 PurposeModel source= converter.convert(purpose,PurposeModel.class); 
		 Utils.copyNotNulls(source,target); 
		 return converter.convert(purposeRepository.save(target), PurposeTo.class);
	}

	/**
	 * 
	 * @param purposeRepository
	 */
	@Autowired
	public PurposeImpl(PurposeRepository purposeRepository){
		this.purposeRepository =purposeRepository;
	}

	@Override
	public Page<PurposeTo> findPurposesByServiceID(int idService) {
		// TODO Auto-generated method stub
		return null;
	}

}