///////////////////////////////////////////////////////////
//  RequestService.java
//  Macromedia ActionScript Implementation of the Interface RequestService
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:43:18 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.RequestTo;
import org.ebs.services.to.Input.RequestInput;
import org.ebs.services.to.PurposeTo;
import org.ebs.services.to.WorkflowCFValueTo;
import org.ebs.services.to.WorkflowInstanceTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:43:18 AM
 */
public interface RequestService {

	/**
	 * 
	 * @param Request
	 */
	public RequestTo createRequest(RequestInput Request);

	/**
	 * 
	 * @param requestId
	 */
	public int deleteRequest(int requestId);

	/**
	 * 
	 * @param requestId
	 */
	public Optional<PurposeTo> findPurpose(int requestId);

	/**
	 * 
	 * @param requestId
	 */
	public Optional<RequestTo> findRequest(int requestId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<RequestTo> findRequests(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param requestId
	 */
	public Set<WorkflowCFValueTo> findWorkflowCFValues(int requestId);

	/**
	 * 
	 * @param requestId
	 */
	public Optional<WorkflowInstanceTo> findWorkflowInstance(int requestId);

	/**
	 * 
	 * @param request
	 */
	public RequestTo modifyRequest(RequestInput request);

}