///////////////////////////////////////////////////////////
//  RequestService.java
//  Macromedia ActionScript Implementation of the Interface RequestService
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:52 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.RequestTo;
import org.ebs.services.to.Input.RequestInput;
import org.ebs.services.to.CfValueTo;
import org.ebs.services.to.WfInstanceTo;
import org.ebs.services.to.PersonTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:52 AM
 */
public interface RequestService {

	/**
	 * 
	 * @param Request
	 */
	public RequestTo createRequest(RequestInput Request);

	/**
	 * 
	 * @param requestId
	 */
	public int deleteRequest(int requestId);

	/**
	 * 
	 * @param requestId
	 */
	public Set<CfValueTo> findCfValues(int requestId);

	/**
	 * 
	 * @param requestId
	 */
	public Optional<PersonTo> findPerson(int requestId);

	/**
	 * 
	 * @param requestId
	 */
	public Optional<RequestTo> findRequest(int requestId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<RequestTo> findRequests(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param requestId
	 */
	public Optional<WfInstanceTo> findWfInstance(int requestId);

	/**
	 * 
	 * @param request
	 */
	public RequestTo modifyRequest(RequestInput request);

}