///////////////////////////////////////////////////////////
//  RoleActionService.java
//  Macromedia ActionScript Implementation of the Interface RoleActionService
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 12:20:02 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.services.to.RoleActionTo;
import org.ebs.services.to.Input.RoleActionInput;
import org.ebs.services.to.RoleTo;
import org.ebs.services.to.ActionTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 12:20:02 AM
 */
public interface RoleActionService {

	/**
	 * 
	 * @param RoleAction
	 */
	public RoleActionTo createRoleAction(RoleActionInput RoleAction);

	/**
	 * 
	 * @param roleActionId
	 */
	public int deleteRoleAction(int roleActionId);

	/**
	 * 
	 * @param roleactionId
	 */
	public Optional<ActionTo> findAction(int roleactionId);

	/**
	 * 
	 * @param roleactionId
	 */
	public Optional<RoleTo> findRole(int roleactionId);

	/**
	 * 
	 * @param roleActionId
	 */
	public Optional<RoleActionTo> findRoleAction(int roleActionId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<RoleActionTo> findRoleActions(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param roleAction
	 */
	public RoleActionTo modifyRoleAction(RoleActionInput roleAction);

}