///////////////////////////////////////////////////////////
//  RoleService.java
//  Macromedia ActionScript Implementation of the Interface RoleService
//  Generated by Enterprise Architect
//  Created on:      23-Jul-2020 10:47:05 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.RoleTo;
import org.ebs.services.to.Input.RoleInput;
import org.ebs.services.to.RoleActionTo;
import org.ebs.services.to.UserTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 23-Jul-2020 10:47:05 PM
 */
public interface RoleService {

	/**
	 * 
	 * @param Role
	 */
	public RoleTo createRole(RoleInput Role);

	/**
	 * 
	 * @param roleId
	 */
	public int deleteRole(int roleId);

	/**
	 * 
	 * @param roleId
	 */
	public Optional<RoleTo> findRole(int roleId);

	/**
	 * 
	 * @param roleId
	 */
	public Set<RoleActionTo> findRoleActions(int roleId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<RoleTo> findRoles(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param role
	 */
	public RoleTo modifyRole(RoleInput role);

}