///////////////////////////////////////////////////////////
//  SchemeServiceImpl.java
//  Macromedia ActionScript Implementation of the Class SchemeServiceImpl
//  Generated by Enterprise Architect
//  Created on:      13-Jul-2020 5:07:16 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import org.ebs.model.repos.SchemeRepository;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.Page;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.ebs.util.Utils;
import org.springframework.core.convert.ConversionService;
import java.util.stream.Collectors;
import java.util.Set;
import org.ebs.services.to.SchemeTo;
import org.ebs.services.to.Input.SchemeInput;
import org.ebs.model.SchemeModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Jul-2020 5:07:16 PM
 */
@Service @Transactional(readOnly = true)
  class SchemeServiceImpl implements SchemeService {

	private SchemeRepository schemeRepository;
	private ConversionService converter;

	/**
	 * 
	 * @param Scheme
	 */
	@Override @Transactional(readOnly = false)
	public SchemeTo createScheme(SchemeInput Scheme){
		SchemeModel model = converter.convert(Scheme,SchemeModel.class); 
		 model.setId(0);
		  
		 model= schemeRepository.save(model); 
		 return converter.convert(model, SchemeTo.class); 
	}

	/**
	 * 
	 * @param schemeId
	 */
	@Override @Transactional(readOnly = false)
	public int deleteScheme(int schemeId){
		SchemeModel scheme = schemeRepository.findById(schemeId).orElseThrow(() -> new RuntimeException("Scheme not found")); 
		 scheme.setDeleted(true); 
		  schemeRepository.save(scheme); 
		 return schemeId;
	}

	/**
	 * 
	 * @param schemeId
	 */
	@Override
	public Optional<SchemeTo> findScheme(int schemeId){
		if(schemeId <1) 
		 {return Optional.empty();} 
		 return schemeRepository.findById(schemeId).filter(r -> !r.getDeleted().booleanValue()).map(r -> converter.convert(r,SchemeTo.class));
	}

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	@Override
	public Page<SchemeTo> findSchemes(PageInput page, SortInput sort, List<FilterInput> filters){
		return schemeRepository.findByCriteria(SchemeModel.class,filters,sort,page).map(r -> converter.convert(r,SchemeTo.class));
	}

	/**
	 * 
	 * @param scheme
	 */
	@Override @Transactional(readOnly = false)
	public SchemeTo modifyScheme(SchemeInput scheme){
		SchemeModel target= schemeRepository.findById(scheme.getId()).orElseThrow(() -> new RuntimeException("Scheme not found")); 
		 SchemeModel source= converter.convert(scheme,SchemeModel.class); 
		 Utils.copyNotNulls(source,target); 
		 return converter.convert(schemeRepository.save(target), SchemeTo.class);
	}

	/**
	 * 
	 * @param converter
	 * @param schemeRepository
	 */
	@Autowired
	public SchemeServiceImpl(ConversionService converter, SchemeRepository schemeRepository){
		this.schemeRepository =schemeRepository; 
		 this.converter = converter;
	}

}