///////////////////////////////////////////////////////////
//  ServiceService.java
//  Macromedia ActionScript Implementation of the Interface ServiceService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:17 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;

import org.ebs.services.to.ServiceTo;
import org.ebs.services.to.Input.ServiceInput;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:17 PM
 */
public interface ServiceService {

	/**
	 * 
	 * @param Service
	 */
	public ServiceTo createService(ServiceInput Service);

	/**
	 * 
	 * @param idservice
	 */
	public int deleteService(int idservice);

	/**
	 * 
	 * @param serviceId
	 */
	public Optional<ServiceTo> findService(int serviceId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<ServiceTo> findServices(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param service
	 */
	public ServiceTo modifyService(ServiceInput service);

}