///////////////////////////////////////////////////////////
//  StyleThemeService.java
//  Macromedia ActionScript Implementation of the Interface StyleThemeService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:22 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;

import org.ebs.services.to.StyleThemeTo;
import org.ebs.services.to.Input.StyleThemeInput;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:22 PM
 */
public interface StyleThemeService {

	/**
	 * 
	 * @param StyleTheme
	 */
	public StyleThemeTo createStyleTheme(StyleThemeInput StyleTheme);

	/**
	 * 
	 * @param idstyletheme
	 */
	public int deleteStyleTheme(int idstyletheme);

	/**
	 * 
	 * @param stylethemeId
	 */
	public Optional<StyleThemeTo> findStyleTheme(int stylethemeId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<StyleThemeTo> findStyleThemes(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param styletheme
	 */
	public StyleThemeTo modifyStyleTheme(StyleThemeInput styletheme);

}