///////////////////////////////////////////////////////////
//  TechnologyPlatformService.java
//  Macromedia ActionScript Implementation of the Interface TechnologyPlatformService
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:17 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.TechnologyPlatformTo;
import org.ebs.services.to.Input.TechnologyPlatformInput;
import org.ebs.services.to.VendorTo;
import org.ebs.services.to.AssayclassTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:17 AM
 */
public interface TechnologyPlatformService {

	/**
	 * 
	 * @param TechnologyPlatform
	 */
	public TechnologyPlatformTo createTechnologyPlatform(TechnologyPlatformInput TechnologyPlatform);

	/**
	 * 
	 * @param technologyPlatformId
	 */
	public int deleteTechnologyPlatform(int technologyPlatformId);

	/**
	 * 
	 * @param technologyPlatformId
	 */
	public Set<AssayclassTo> findAssayclasss(int technologyPlatformId);

	/**
	 * 
	 * @param technologyPlatformId
	 */
	public Optional<TechnologyPlatformTo> findTechnologyPlatform(int technologyPlatformId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<TechnologyPlatformTo> findTechnologyPlatforms(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param technologyPlatformId
	 */
	public Set<VendorTo> findVendors(int technologyPlatformId);

	/**
	 * 
	 * @param technologyPlatform
	 */
	public TechnologyPlatformTo modifyTechnologyPlatform(TechnologyPlatformInput technologyPlatform);

}