///////////////////////////////////////////////////////////
//  TechnologyPlatformServiceImpl.java
//  Macromedia ActionScript Implementation of the Class TechnologyPlatformServiceImpl
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:06:14 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import org.ebs.model.repos.TechnologyPlatformRepository;
import org.ebs.model.repos.AssayclassRepository;
import org.ebs.model.repos.VendorRepository;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.Page;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.ebs.util.Utils;
import org.springframework.core.convert.ConversionService;
import java.util.stream.Collectors;
import java.util.Set;
import org.ebs.services.to.TechnologyPlatformTo;
import org.ebs.services.to.Input.TechnologyPlatformInput;
import org.ebs.model.TechnologyPlatformModel;
import org.ebs.services.to.AssayclassTo;
import org.ebs.services.to.VendorTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:06:14 AM
 */
@Service @Transactional(readOnly = true)
  class TechnologyPlatformServiceImpl implements TechnologyPlatformService {

	private TechnologyPlatformRepository technologyplatformRepository;
	private ConversionService converter;
	public AssayclassRepository assayclassRepository;
	public VendorRepository vendorRepository;

	/**
	 *
	 * @param TechnologyPlatform
	 */
	@Override @Transactional(readOnly = false)
	public TechnologyPlatformTo createtechnologyplatform(TechnologyPlatformInput TechnologyPlatform){
		TechnologyPlatformModel model = converter.convert(TechnologyPlatform,TechnologyPlatformModel.class);
		 model.setId(0);

		 model= technologyplatformRepository.save(model);
		 return converter.convert(model, TechnologyPlatformTo.class);
	}

	/**
	 *
	 * @param technologyplatformId
	 */
	@Override @Transactional(readOnly = false)
	public int deletetechnologyplatform(int technologyplatformId){
		TechnologyPlatformModel technologyplatform = technologyplatformRepository.findById(technologyplatformId).orElseThrow(() -> new RuntimeException("TechnologyPlatform not found"));
		 technologyplatform.setDeleted(true);
		  technologyplatformRepository.save(technologyplatform);
		 return technologyplatformId;
	}

	/**
	 *
	 * @param technologyplatformId
	 */
	public Set<AssayclassTo> findassayclasss(int technologyplatformId){
		return technologyplatformRepository.findById(technologyplatformId).get().getAssayclasss().stream().map(e->converter.convert(e, AssayclassTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param technologyplatformId
	 */
	@Override
	public Optional<TechnologyPlatformTo> findtechnologyplatform(int technologyplatformId){
		if(technologyplatformId <1)
		 {return Optional.empty();}
		 return technologyplatformRepository.findById(technologyplatformId).filter(r -> !r.getDeleted().booleanValue()).map(r -> converter.convert(r,TechnologyPlatformTo.class));
	}

	/**
	 *
	 * @param page
	 * @param sort
	 * @param filters
	 */
	@Override
	public Page<TechnologyPlatformTo> findtechnologyplatforms(PageInput page, SortInput sort, List<FilterInput> filters, boolean disjunctionFilters){
		return technologyplatformRepository.findByCriteria(TechnologyPlatformModel.class,filters,sort,page,disjunctionFilters).map(r -> converter.convert(r,TechnologyPlatformTo.class));
	}

	/**
	 *
	 * @param technologyplatformId
	 */
	public Set<VendorTo> findvendors(int technologyplatformId){
		return vendorRepository.findByTechnologyplatformId(technologyplatformId).stream().map(e -> converter.convert(e,VendorTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param technologyplatform
	 */
	@Override @Transactional(readOnly = false)
	public TechnologyPlatformTo modifytechnologyplatform(TechnologyPlatformInput technologyplatform){
		TechnologyPlatformModel target= technologyplatformRepository.findById(technologyplatform.getId()).orElseThrow(() -> new RuntimeException("TechnologyPlatform not found"));
		 TechnologyPlatformModel source= converter.convert(technologyplatform,TechnologyPlatformModel.class);
		 Utils.copyNotNulls(source,target);
		 return converter.convert(technologyplatformRepository.save(target), TechnologyPlatformTo.class);
	}

	/**
	 *
	 * @param vendorRepository
	 * @param assayclassRepository
	 * @param converter
	 * @param technologyplatformRepository
	 */
	@Autowired
	public TechnologyPlatformServiceImpl(VendorRepository vendorRepository, AssayclassRepository assayclassRepository, ConversionService converter, TechnologyPlatformRepository technologyplatformRepository){
		this.technologyplatformRepository =technologyplatformRepository;
		 this.converter = converter;
		 this.assayclassRepository = assayclassRepository;
		 this.vendorRepository = vendorRepository;
	}

}