///////////////////////////////////////////////////////////
//  ThemeStyleService.java
//  Macromedia ActionScript Implementation of the Interface ThemeStyleService
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 12:07:15 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.services.to.Input.ThemeStyleInput;
import org.ebs.services.to.ThemeStyleTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 12:07:15 AM
 */
public interface ThemeStyleService {

	/**
	 * 
	 * @param ThemeStyle
	 */
	public ThemeStyleTo createThemeStyle(ThemeStyleInput ThemeStyle);

	/**
	 * 
	 * @param idthemestyle
	 */
	public int deleteThemeStyle(int idthemestyle);

	/**
	 * 
	 * @param themestyleId
	 */
	public Optional<ThemeStyleTo> findThemeStyle(int themestyleId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<ThemeStyleTo> findThemeStyles(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param themestyle
	 */
	public ThemeStyleTo modifyThemeStyle(ThemeStyleInput themestyle);

}