///////////////////////////////////////////////////////////
//  TraitService.java
//  Macromedia ActionScript Implementation of the Interface TraitService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:29 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;

import org.ebs.services.to.TraitTo;
import org.ebs.services.to.Input.TraitInput;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:29 PM
 */
public interface TraitService {

	/**
	 * 
	 * @param Trait
	 */
	public TraitTo createTrait(TraitInput Trait);

	/**
	 * 
	 * @param idtrait
	 */
	public int deleteTrait(int idtrait);

	/**
	 * 
	 * @param traitId
	 */
	public Optional<TraitTo> findTrait(int traitId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<TraitTo> findTraits(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param trait
	 */
	public TraitTo modifyTrait(TraitInput trait);

}