///////////////////////////////////////////////////////////
//  TraitService.java
//  Macromedia ActionScript Implementation of the Interface TraitService
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:06:20 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.TraitTo;
import org.ebs.services.to.Input.TraitInput;
import org.ebs.services.to.TraitClassTo;
import org.ebs.services.to.AssayGeneTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:06:20 AM
 */
public interface TraitService {

	/**
	 * 
	 * @param Trait
	 */
	public TraitTo createtrait(TraitInput Trait);

	/**
	 * 
	 * @param traitId
	 */
	public int deletetrait(int traitId);

	/**
	 * 
	 * @param traitId
	 */
	public Set<AssayGeneTo> findassaygenes(int traitId);

	/**
	 * 
	 * @param traitId
	 */
	public Optional<TraitTo> findtrait(int traitId);

	/**
	 * 
	 * @param traitId
	 */
	public Optional<TraitClassTo> findtraitclass(int traitId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<TraitTo> findtraits(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param trait
	 */
	public TraitTo modifytrait(TraitInput trait);

}