///////////////////////////////////////////////////////////
//  VendorService.java
//  Macromedia ActionScript Implementation of the Interface VendorService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:34 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.VendorRepository;
import org.springframework.stereotype.Service;
import org.ebs.services.to.Input.VendorInput;
import org.ebs.services.to.VendorTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:34 PM
 */
public interface VendorService {

	/**
	 * 
	 * @param Vendor
	 */
	public VendorTo createVendor(VendorInput Vendor);

	/**
	 * 
	 * @param idvendor
	 */
	public int deleteVendor(int idvendor);

	/**
	 * 
	 * @param vendorId
	 */
	public Optional<VendorTo> findVendor(int vendorId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<VendorTo> findVendors(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param vendor
	 */
	public VendorTo modifyVendor(VendorInput vendor);

}