///////////////////////////////////////////////////////////
//  WorkflowPhaseService.java
//  Macromedia ActionScript Implementation of the Interface WorkflowPhaseService
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:44:04 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import java.util.Set;
import org.ebs.services.to.WorkflowPhaseTo;
import org.ebs.services.to.Input.WorkflowPhaseInput;
import org.ebs.services.to.WorkflowStageTo;
import org.ebs.services.to.WorkflowTo;
import org.ebs.services.to.HtmlTagTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:44:04 AM
 */
public interface WorkflowPhaseService {

	/**
	 * 
	 * @param WorkflowPhase
	 */
	public WorkflowPhaseTo createWorkflowPhase(WorkflowPhaseInput WorkflowPhase);

	/**
	 * 
	 * @param workflowphaseId
	 */
	public int deleteWorkflowPhase(int workflowphaseId);

	/**
	 * 
	 * @param workflowphaseId
	 */
	public Optional<HtmlTagTo> findHtmlTag(int workflowphaseId);

	/**
	 * 
	 * @param workflowphaseId
	 */
	public Optional<WorkflowTo> findWorkflow(int workflowphaseId);

	/**
	 * 
	 * @param workflowphaseId
	 */
	public Optional<WorkflowPhaseTo> findWorkflowPhase(int workflowphaseId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<WorkflowPhaseTo> findWorkflowPhases(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param workflowphaseId
	 */
	public Set<WorkflowStageTo> findWorkflowStages(int workflowphaseId);

	/**
	 * 
	 * @param workflowphase
	 */
	public WorkflowPhaseTo modifyWorkflowPhase(WorkflowPhaseInput workflowphase);

}