///////////////////////////////////////////////////////////
//  WorkflowService.java
//  Macromedia ActionScript Implementation of the Interface WorkflowService
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:37 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.WorkflowRepository;
import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.ebs.services.to.WorkflowTo;
import org.ebs.services.to.Input.WorkflowInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:37 PM
 */
public interface WorkflowService {

	/**
	 * 
	 * @param Workflow
	 */
	public WorkflowTo createWorkflow(WorkflowInput Workflow);

	/**
	 * 
	 * @param idworkflow
	 */
	public int deleteWorkflow(int idworkflow);

	/**
	 * 
	 * @param workflowId
	 */
	public Optional<WorkflowTo> findWorkflow(int workflowId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<WorkflowTo> findWorkflows(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param workflow
	 */
	public WorkflowTo modifyWorkflow(WorkflowInput workflow);

}