///////////////////////////////////////////////////////////
//  WorkflowCFValueService.java
//  Macromedia ActionScript Implementation of the Interface WorkflowCFValueService
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:33 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.services.to.WorkflowCFValueTo;
import org.ebs.services.to.Input.WorkflowCFValueInput;
import org.ebs.services.to.RequestTo;
import org.ebs.services.to.WorkflowNodeCFTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:33 AM
 */
public interface WorkflowCFValueService {

	/**
	 * 
	 * @param WorkflowCFValue
	 */
	public WorkflowCFValueTo createWorkflowCFValue(WorkflowCFValueInput WorkflowCFValue);

	/**
	 * 
	 * @param workflowCFValueId
	 */
	public int deleteWorkflowCFValue(int workflowCFValueId);

	/**
	 * 
	 * @param workflowCFValueId
	 */
	public Optional<RequestTo> findRequest(int workflowCFValueId);

	/**
	 * 
	 * @param workflowCFValueId
	 */
	public Optional<WorkflowCFValueTo> findWorkflowCFValue(int workflowCFValueId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<WorkflowCFValueTo> findWorkflowCFValues(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param workflowCFValueId
	 */
	public Optional<WorkflowNodeCFTo> findWorkflowNodeCF(int workflowCFValueId);

	/**
	 * 
	 * @param workflowCFValue
	 */
	public WorkflowCFValueTo modifyWorkflowCFValue(WorkflowCFValueInput workflowCFValue);

}