///////////////////////////////////////////////////////////
//  WorkflowNodeCFServiceImpl.java
//  Macromedia ActionScript Implementation of the Class WorkflowNodeCFServiceImpl
//  Generated by Enterprise Architect
//  Created on:      07-Aug-2020 3:02:39 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import org.ebs.model.repos.WorkflowCFTypeRepository;
import org.ebs.model.HtmlTagModel;
import org.ebs.model.repos.HtmlTagRepository;
import org.ebs.model.EntityReferenceModel;
import org.ebs.model.repos.EntityReferenceRepository;
import org.ebs.model.WorkflowNodeModel;
import org.ebs.model.repos.WorkflowNodeRepository;
import org.ebs.model.repos.WorkflowNodeCFRepository;
import org.ebs.model.repos.WorkflowCFValueRepository;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.Page;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.ebs.util.Utils;
import org.springframework.core.convert.ConversionService;
import java.util.stream.Collectors;
import java.util.Set;
import org.ebs.model.WorkflowCFTypeModel;
import org.ebs.services.to.WorkflowNodeCFTo;
import org.ebs.services.to.Input.WorkflowNodeCFInput;
import org.ebs.model.WorkflowNodeCFModel;
import org.ebs.services.to.HtmlTagTo;
import org.ebs.services.to.EntityReferenceTo;
import org.ebs.services.to.WorkflowNodeTo;
import org.ebs.services.to.WorkflowCFValueTo;
import org.ebs.services.to.WorkflowCFTypeTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Aug-2020 3:02:39 PM
 */
@Service @Transactional(readOnly = true)
  class WorkflowNodeCFServiceImpl implements WorkflowNodeCFService {

	private WorkflowNodeCFRepository workflownodecfRepository;
	private ConversionService converter;
	private WorkflowCFTypeRepository workflowcftypeRepository;
	private HtmlTagRepository htmltagRepository;
	private EntityReferenceRepository entityreferenceRepository;
	private WorkflowNodeRepository workflownodeRepository;
	public WorkflowCFValueRepository workflowcfvalueRepository;

	/**
	 * 
	 * @param WorkflowNodeCF
	 */
	@Override @Transactional(readOnly = false)
	public WorkflowNodeCFTo createWorkflowNodeCF(WorkflowNodeCFInput WorkflowNodeCF){
		WorkflowNodeCFModel model = converter.convert(WorkflowNodeCF,WorkflowNodeCFModel.class); 
		 model.setId(0);
		 WorkflowCFTypeModel workflowcftypeModel = workflowcftypeRepository.findById(WorkflowNodeCF.getworkflowcftype().getId()).get(); 
		model.setworkflowcftype(workflowcftypeModel); 
		HtmlTagModel htmltagModel = htmltagRepository.findById(WorkflowNodeCF.gethtmltag().getId()).get(); 
		model.sethtmltag(htmltagModel); 
		EntityReferenceModel entityreferenceModel = entityreferenceRepository.findById(WorkflowNodeCF.getentityreference().getId()).get(); 
		model.setentityreference(entityreferenceModel); 
		WorkflowNodeModel workflownodeModel = workflownodeRepository.findById(WorkflowNodeCF.getworkflownode().getId()).get(); 
		model.setworkflownode(workflownodeModel); 
		 
		 model= workflownodecfRepository.save(model); 
		 return converter.convert(model, WorkflowNodeCFTo.class); 
	}

	/**
	 * 
	 * @param workflownodecfId
	 */
	@Override @Transactional(readOnly = false)
	public int deleteWorkflowNodeCF(int workflownodecfId){
		WorkflowNodeCFModel workflownodecf = workflownodecfRepository.findById(workflownodecfId).orElseThrow(() -> new RuntimeException("WorkflowNodeCF not found")); 
		 workflownodecf.setDeleted(true); 
		  workflownodecfRepository.save(workflownodecf); 
		 return workflownodecfId;
	}

	/**
	 * 
	 * @param workflownodecfId
	 */
	public Optional<EntityReferenceTo> findEntityReference(int workflownodecfId){
		return workflownodecfRepository.findById(workflownodecfId).map(r -> converter.convert(r.getentityreference(),EntityReferenceTo.class));
	}

	/**
	 * 
	 * @param workflownodecfId
	 */
	public Optional<HtmlTagTo> findHtmlTag(int workflownodecfId){
		return workflownodecfRepository.findById(workflownodecfId).map(r -> converter.convert(r.gethtmltag(),HtmlTagTo.class));
	}

	/**
	 * 
	 * @param workflownodecfId
	 */
	public Optional<WorkflowCFTypeTo> findWorkflowCFType(int workflownodecfId){
		return workflownodecfRepository.findById(workflownodecfId).map(r -> converter.convert(r.getworkflowcftype(),WorkflowCFTypeTo.class));
	}

	/**
	 * 
	 * @param workflownodecfId
	 */
	public Set<WorkflowCFValueTo> findWorkflowCFValues(int workflownodecfId){
		return workflowcfvalueRepository.findByWorkflownodecfId(workflownodecfId).stream().map(e -> converter.convert(e,WorkflowCFValueTo.class)).collect(Collectors.toSet());
	}

	/**
	 * 
	 * @param workflownodecfId
	 */
	public Optional<WorkflowNodeTo> findWorkflowNode(int workflownodecfId){
		return workflownodecfRepository.findById(workflownodecfId).map(r -> converter.convert(r.getworkflownode(),WorkflowNodeTo.class));
	}

	/**
	 * 
	 * @param workflownodecfId
	 */
	@Override
	public Optional<WorkflowNodeCFTo> findWorkflowNodeCF(int workflownodecfId){
		if(workflownodecfId <1) 
		 {return Optional.empty();} 
		 return workflownodecfRepository.findById(workflownodecfId).filter(r -> !r.getDeleted().booleanValue()).map(r -> converter.convert(r,WorkflowNodeCFTo.class));
	}

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	@Override
	public Page<WorkflowNodeCFTo> findWorkflowNodeCFs(PageInput page, SortInput sort, List<FilterInput> filters){
		return workflownodecfRepository.findByCriteria(WorkflowNodeCFModel.class,filters,sort,page).map(r -> converter.convert(r,WorkflowNodeCFTo.class));
	}

	/**
	 * 
	 * @param workflownodecf
	 */
	@Override @Transactional(readOnly = false)
	public WorkflowNodeCFTo modifyWorkflowNodeCF(WorkflowNodeCFInput workflownodecf){
		WorkflowNodeCFModel target= workflownodecfRepository.findById(workflownodecf.getId()).orElseThrow(() -> new RuntimeException("WorkflowNodeCF not found")); 
		 WorkflowNodeCFModel source= converter.convert(workflownodecf,WorkflowNodeCFModel.class); 
		 Utils.copyNotNulls(source,target); 
		 return converter.convert(workflownodecfRepository.save(target), WorkflowNodeCFTo.class);
	}

	/**
	 * 
	 * @param converter
	 * @param workflowcfvalueRepository
	 * @param workflowcftypeRepository
	 * @param htmltagRepository
	 * @param entityreferenceRepository
	 * @param workflownodeRepository
	 * @param workflownodecfRepository
	 */
	@Autowired
	public WorkflowNodeCFServiceImpl(ConversionService converter, WorkflowCFValueRepository workflowcfvalueRepository, WorkflowCFTypeRepository workflowcftypeRepository, HtmlTagRepository htmltagRepository, EntityReferenceRepository entityreferenceRepository, WorkflowNodeRepository workflownodeRepository, WorkflowNodeCFRepository workflownodecfRepository){
		this.workflownodecfRepository =workflownodecfRepository; 
		 this.converter = converter;
		 this.workflowcfvalueRepository = workflowcfvalueRepository;
		 this.workflowcftypeRepository = workflowcftypeRepository;
		 this.htmltagRepository = htmltagRepository;
		 this.entityreferenceRepository = entityreferenceRepository;
		 this.workflownodeRepository = workflownodeRepository;
	}

}