///////////////////////////////////////////////////////////
//  WorkflowNodeServiceImpl.java
//  Macromedia ActionScript Implementation of the Class WorkflowNodeServiceImpl
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:45:11 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import org.ebs.model.EntityReferenceModel;
import org.ebs.model.repos.EntityReferenceRepository;
import org.ebs.model.HtmlTagModel;
import org.ebs.model.repos.HtmlTagRepository;
import org.ebs.model.ProcessModel;
import org.ebs.model.repos.ProcessRepository;
import org.ebs.model.ModuleModel;
import org.ebs.model.repos.ModuleRepository;
import org.ebs.model.repos.WorkflowNodeRepository;
import org.ebs.model.repos.WorkflowStageRepository;
import org.ebs.model.repos.ActionRepository;
import org.ebs.model.WorkflowModel;
import org.ebs.model.repos.WorkflowRepository;
import org.ebs.model.repos.WorkflowEventRepository;
import org.ebs.model.repos.WorkflowNodeCFRepository;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.Page;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.ebs.util.Utils;
import org.springframework.core.convert.ConversionService;
import java.util.stream.Collectors;
import java.util.Set;
import org.ebs.services.to.WorkflowNodeTo;
import org.ebs.services.to.Input.WorkflowNodeInput;
import org.ebs.model.WorkflowNodeModel;
import org.ebs.services.to.WorkflowTo;
import org.ebs.services.to.ActionTo;
import org.ebs.services.to.EntityReferenceTo;
import org.ebs.services.to.WorkflowEventTo;
import org.ebs.services.to.HtmlTagTo;
import org.ebs.services.to.ProcessTo;
import org.ebs.services.to.WorkflowStageTo;
import org.ebs.services.to.ModuleTo;
import org.ebs.services.to.WorkflowNodeCFTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:45:11 PM
 */
@Service @Transactional(readOnly = true)
  class WorkflowNodeServiceImpl implements WorkflowNodeService {

	private WorkflowNodeRepository workflownodeRepository;
	private ConversionService converter;
	private WorkflowRepository workflowRepository;
	private EntityReferenceRepository entityreferenceRepository;
	private HtmlTagRepository htmltagRepository;
	private ProcessRepository processRepository;
	private ModuleRepository moduleRepository;
	private WorkflowStageRepository workflowstageRepository;
	private ActionRepository actionRepository;
	private WorkflowEventRepository workfloweventRepository;
	private WorkflowNodeCFRepository workflownodecfRepository;

	/**
	 *
	 * @param WorkflowNode
	 */
	@Override @Transactional(readOnly = false)
	public WorkflowNodeTo createWorkflowNode(WorkflowNodeInput WorkflowNode){
		WorkflowNodeModel model = converter.convert(WorkflowNode,WorkflowNodeModel.class);
		 model.setId(0);
		initWorkflowNodeModel(WorkflowNode, model);

		 model= workflownodeRepository.save(model);
		 return converter.convert(model, WorkflowNodeTo.class);
	}

	void initWorkflowNodeModel(WorkflowNodeInput workflowNode, WorkflowNodeModel model) {
		Optional<WorkflowNodeInput> optWFN = Optional.of(workflowNode);

		WorkflowModel workflowModel = optWFN
			.map(wfn -> wfn.getWorkflow())
			.map(w -> workflowRepository.findById(w.getId())
				.orElseThrow(() -> new RuntimeException("workflow does not exist")))
			.orElse(null);
		model.setWorkflow(workflowModel);

		EntityReferenceModel entityreferenceModel = optWFN
			.map(wfn -> wfn.getEntityreference())
			.map(er -> entityreferenceRepository.findById(er.getId())
				.orElseThrow(() -> new RuntimeException("entityreference does not exist")))
			.orElse(null);
		model.setEntityreference(entityreferenceModel);

		HtmlTagModel htmltagModel = optWFN
			.map(wfn -> wfn.getHtmltag())
			.map(ht -> htmltagRepository.findById(ht.getId())
				.orElseThrow(() -> new RuntimeException("htmltag does not exist")))
			.orElse(null);
		model.setHtmltag(htmltagModel);

		ProcessModel processModel = optWFN
			.map(wfn -> wfn.getProcess())
			.map(p -> processRepository.findById(p.getId())
				.orElseThrow(() -> new RuntimeException("process does not exist")))
			.orElse(null);
		model.setProcess(processModel);

		ModuleModel moduleModel = optWFN
			.map(wfn -> wfn.getModule())
			.map(m -> moduleRepository.findById(m.getId())
				.orElseThrow(()-> new RuntimeException("module does not exist")))
			.orElse(null);
		model.setModule(moduleModel);

	}



	/**
	 *
	 * @param workflowNodeId
	 */
	@Override @Transactional(readOnly = false)
	public int deleteWorkflowNode(int workflowNodeId){
		WorkflowNodeModel workflownode = workflownodeRepository.findById(workflowNodeId).orElseThrow(() -> new RuntimeException("WorkflowNode not found"));
		 workflownode.setDeleted(true);
		  workflownodeRepository.save(workflownode);
		 return workflowNodeId;
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Set<ActionTo> findActions(int workflownodeId){
		return actionRepository.findByWorkflownodeId(workflownodeId).stream().map(e -> converter.convert(e,ActionTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Optional<EntityReferenceTo> findEntityReference(int workflownodeId){
		return workflownodeRepository.findById(workflownodeId).map(r -> converter.convert(r.getEntityreference(),EntityReferenceTo.class));
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Optional<HtmlTagTo> findHtmlTag(int workflownodeId){
		return workflownodeRepository.findById(workflownodeId).map(r -> converter.convert(r.getHtmltag(),HtmlTagTo.class));
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Optional<ModuleTo> findModule(int workflownodeId){
		return workflownodeRepository.findById(workflownodeId).map(r -> converter.convert(r.getModule(),ModuleTo.class));
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Optional<ProcessTo> findProcess(int workflownodeId){
		return workflownodeRepository.findById(workflownodeId).map(r -> converter.convert(r.getProcess(),ProcessTo.class));
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Optional<WorkflowTo> findWorkflow(int workflownodeId){
		return workflownodeRepository.findById(workflownodeId).map(r -> converter.convert(r.getWorkflow(),WorkflowTo.class));
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Set<WorkflowEventTo> findWorkflowEvents(int workflownodeId){
		return workfloweventRepository.findByWorkflownodeId(workflownodeId).stream().map(e -> converter.convert(e,WorkflowEventTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param workflowNodeId
	 */
	@Override
	public Optional<WorkflowNodeTo> findWorkflowNode(int workflowNodeId){
		if(workflowNodeId <1)
		 {return Optional.empty();}
		 return workflownodeRepository.findById(workflowNodeId).filter(r -> !r.getDeleted().booleanValue()).map(r -> converter.convert(r,WorkflowNodeTo.class));
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Set<WorkflowNodeCFTo> findWorkflowNodeCFs(int workflownodeId){
		return workflownodecfRepository.findByWorkflownodeId(workflownodeId).stream().map(e -> converter.convert(e,WorkflowNodeCFTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param page
	 * @param sort
	 * @param filters
	 */
	@Override
	public Page<WorkflowNodeTo> findWorkflowNodes(PageInput page, SortInput sort, List<FilterInput> filters, boolean disjunctionFilters){
		return workflownodeRepository.findByCriteria(WorkflowNodeModel.class,filters,sort,page,disjunctionFilters).map(r -> converter.convert(r,WorkflowNodeTo.class));
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Set<WorkflowTo> findWorkflows(int workflownodeId){
		return workflowRepository.findByWorkflownodeId(workflownodeId).stream().map(e -> converter.convert(e,WorkflowTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param workflownodeId
	 */
	public Set<WorkflowStageTo> findWorkflowStages(int workflownodeId){
		return workflownodeRepository.findById(workflownodeId).get().getWorkflowstages().stream().map(e->converter.convert(e, WorkflowStageTo.class)).collect(Collectors.toSet());
	}

	/**
	 *
	 * @param workflowNode
	 */
	@Override @Transactional(readOnly = false)
	public WorkflowNodeTo modifyWorkflowNode(WorkflowNodeInput workflowNode){
		WorkflowNodeModel target= workflownodeRepository.findById(workflowNode.getId()).orElseThrow(() -> new RuntimeException("WorkflowNode not found"));
		 WorkflowNodeModel source= converter.convert(workflowNode,WorkflowNodeModel.class);
		 initWorkflowNodeModel(workflowNode, source);
		 Utils.copyNotNulls(source,target);
		 return converter.convert(workflownodeRepository.save(target), WorkflowNodeTo.class);
	}

	/**
	 *
	 * @param processRepository
	 * @param moduleRepository
	 * @param workflownodecfRepository
	 * @param workflownodeRepository
	 * @param converter
	 * @param workflowstageRepository
	 * @param workflowRepository
	 * @param actionRepository
	 * @param entityreferenceRepository
	 * @param workfloweventRepository
	 * @param htmltagRepository
	 */
	@Autowired
	public WorkflowNodeServiceImpl(ProcessRepository processRepository, ModuleRepository moduleRepository, WorkflowNodeCFRepository workflownodecfRepository, WorkflowNodeRepository workflownodeRepository, ConversionService converter, WorkflowStageRepository workflowstageRepository, WorkflowRepository workflowRepository, ActionRepository actionRepository, EntityReferenceRepository entityreferenceRepository, WorkflowEventRepository workfloweventRepository, HtmlTagRepository htmltagRepository){
		this.workflownodeRepository =workflownodeRepository;
		 this.converter = converter;
		 this.workflowstageRepository = workflowstageRepository;
		 this.workflowRepository = workflowRepository;
		 this.actionRepository = actionRepository;
		 this.entityreferenceRepository = entityreferenceRepository;
		 this.workfloweventRepository = workfloweventRepository;
		 this.htmltagRepository = htmltagRepository;
		 this.processRepository = processRepository;
		 this.moduleRepository = moduleRepository;
		 this.workflownodecfRepository = workflownodecfRepository;
	}

}