///////////////////////////////////////////////////////////
//  WorkflowNodeService.java
//  Macromedia ActionScript Implementation of the Interface WorkflowNodeService
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:34 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services;

import java.util.List;
import java.util.Optional;
import org.ebs.util.FilterInput;
import org.ebs.util.PageInput;
import org.ebs.util.SortInput;
import org.springframework.data.domain.Page;
import org.ebs.util.Utils;
import org.ebs.model.repos.WorkflowNodeRepository;
import org.ebs.services.to.WorkflowNodeTo;
import org.ebs.services.to.Input.WorkflowNodeInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:34 PM
 */
public interface WorkflowNodeService {

	/**
	 * 
	 * @param WorkflowNode
	 */
	public WorkflowNodeTo createWorkflowNode(WorkflowNodeInput WorkflowNode);

	/**
	 * 
	 * @param idworkflownode
	 */
	public int deleteWorkflowNode(int idworkflownode);

	/**
	 * 
	 * @param workflownodeId
	 */
	public Optional<WorkflowNodeTo> findWorkflowNode(int workflownodeId);

	/**
	 * 
	 * @param page
	 * @param sort
	 * @param filters
	 */
	public Page<WorkflowNodeTo> findWorkflowNodes(PageInput page, SortInput sort, List<FilterInput> filters);

	/**
	 * 
	 * @param workflownode
	 */
	public WorkflowNodeTo modifyWorkflowNode(WorkflowNodeInput workflownode);

}