///////////////////////////////////////////////////////////
//  ActionTo.java
//  Macromedia ActionScript Implementation of the Class ActionTo
//  Generated by Enterprise Architect
//  Created on:      09-Aug-2020 4:50:05 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 09-Aug-2020 4:50:05 PM
 */
public class ActionTo implements Serializable {

	private static final long serialVersionUID = -174631809;
	private int id;
	private String description;
	private boolean actionType;
	private String action;
	Set<RoleActionTo> roleactions;
	WorkflowNodeTo workflownode;
	ModuleTo module;
	Set<RoleTo> roles;
	WorkflowStageTo workflowstage;

	public String getaction(){
		return action;
	}

	public boolean getactionType(){
		return actionType;
	}

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public ModuleTo getmodule(){
		return module;
	}

	public Set<RoleActionTo> getroleactions(){
		return roleactions;
	}

	public Set<RoleTo> getroles(){
		return roles;
	}

	public WorkflowNodeTo getworkflownode(){
		return workflownode;
	}

	public WorkflowStageTo getworkflowstage(){
		return workflowstage;
	}

	/**
	 * 
	 * @param action
	 */
	public void setaction(String action){
		this.action = action;
	}

	/**
	 * 
	 * @param actiontype
	 */
	public void setactionType(boolean actiontype){
		this.actionType = actiontype;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param module
	 */
	public void setmodule(ModuleTo module){
		this.module =module;
	}

	/**
	 * 
	 * @param roleaction
	 */
	public void setroleactions(Set<RoleActionTo> roleaction){
		this.roleactions =roleaction;
	}

	/**
	 * 
	 * @param role
	 */
	public void setroles(Set<RoleTo> role){
		this.roles =role;
	}

	/**
	 * 
	 * @param workflownode
	 */
	public void setworkflownode(WorkflowNodeTo workflownode){
		this.workflownode =workflownode;
	}

	/**
	 * 
	 * @param workflowstage
	 */
	public void setworkflowstage(WorkflowStageTo workflowstage){
		this.workflowstage =workflowstage;
	}

	@Override
	public String toString(){
		return "ActionTo [actionType=" + actionType + ",]";
	}

}