///////////////////////////////////////////////////////////
//  AlertRuleTo.java
//  Macromedia ActionScript Implementation of the Class AlertRuleTo
//  Generated by Enterprise Architect
//  Created on:      20-Aug-2020 1:05:21 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 20-Aug-2020 1:05:21 PM
 */
public class AlertRuleTo implements Serializable {

	private static final long serialVersionUID = 520294100;
	private int id;
	private int tenant;
	private String name;
	private String sql;
	private String filterClause;
	AlertTo alert;

	public AlertTo getalert(){
		return alert;
	}

	public String getfilterClause(){
		return filterClause;
	}

	public int getId(){
		return id;
	}

	public String getname(){
		return name;
	}

	public String getsql(){
		return sql;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param alert
	 */
	public void setalert(AlertTo alert){
		this.alert =alert;
	}

	/**
	 * 
	 * @param filterclause
	 */
	public void setfilterClause(String filterclause){
		this.filterClause = filterclause;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param sql
	 */
	public void setsql(String sql){
		this.sql = sql;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	@Override
	public String toString(){
		return "AlertRuleTo []";
	}

}