///////////////////////////////////////////////////////////
//  AssayclassTo.java
//  Macromedia ActionScript Implementation of the Class AssayclassTo
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:43:20 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:43:20 PM
 */
@Getter @Setter
public class AssayclassTo implements Serializable {

	private static final long serialVersionUID = -268477176;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private Set<TechnologyPlatformTo> technologyplatforms;
	private ServiceTo service;

	@Override
	public String toString(){
		return "AssayclassTo []";
	}

}