///////////////////////////////////////////////////////////
//  CountryTo.java
//  Macromedia ActionScript Implementation of the Class CountryTo
//  Generated by Enterprise Architect
//  Created on:      13-Jul-2020 5:06:23 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Jul-2020 5:06:23 PM
 */
public class CountryTo implements Serializable {

	private static final long serialVersionUID = -466034558;
	private int id;
	private String name;
	private String iso3;
	private int number;
	private String full_name;
	private String code;
	Set<VendorTo> vendors;

	public String getcode(){
		return code;
	}

	public String getfull_name(){
		return full_name;
	}

	public int getId(){
		return id;
	}

	public String getiso3(){
		return iso3;
	}

	public String getname(){
		return name;
	}

	public int getnumber(){
		return number;
	}

	public Set<VendorTo> getvendors(){
		return vendors;
	}

	/**
	 * 
	 * @param code
	 */
	public void setcode(String code){
		this.code = code;
	}

	/**
	 * 
	 * @param full_name
	 */
	public void setfull_name(String full_name){
		this.full_name = full_name;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param iso3
	 */
	public void setiso3(String iso3){
		this.iso3 = iso3;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param number
	 */
	public void setnumber(int number){
		this.number = number;
	}

	/**
	 * 
	 * @param vendor
	 */
	public void setvendors(Set<VendorTo> vendor){
		this.vendors =vendor;
	}

	@Override
	public String toString(){
		return "CountryTo [number=" + number + ",]";
	}

}