///////////////////////////////////////////////////////////
//  DelegationTo.java
//  Macromedia ActionScript Implementation of the Class DelegationTo
//  Generated by Enterprise Architect
//  Created on:      13-Jul-2020 5:06:29 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Date;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Jul-2020 5:06:29 PM
 */
public class DelegationTo implements Serializable {

	private static final long serialVersionUID = 7144177;
	private int id;
	private int tenant;
	private Date startDate;
	private Date endDate;
	private String DelegateTo;
	UserTo user;

	public String getDelegateTo(){
		return DelegateTo;
	}

	public Date getendDate(){
		return endDate;
	}

	public int getId(){
		return id;
	}

	public Date getstartDate(){
		return startDate;
	}

	public int getTenant(){
		return tenant;
	}

	public UserTo getuser(){
		return user;
	}

	/**
	 * 
	 * @param delegateto
	 */
	public void setDelegateTo(String delegateto){
		this.DelegateTo = delegateto;
	}

	/**
	 * 
	 * @param enddate
	 */
	public void setendDate(Date enddate){
		this.endDate = enddate;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param startdate
	 */
	public void setstartDate(Date startdate){
		this.startDate = startdate;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param user
	 */
	public void setuser(UserTo user){
		this.user =user;
	}

	@Override
	public String toString(){
		return "DelegationTo []";
	}

}