///////////////////////////////////////////////////////////
//  DonorTo.java
//  Macromedia ActionScript Implementation of the Class DonorTo
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 12:07:00 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import org.ebs.model.PearsonModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 12:07:00 AM
 */
public class DonorTo implements Serializable {

	private static final long serialVersionUID = 265084050;
	private int id;
	private String affiliation;
	private String contactPoint;
	private String indentifier;
	PearsonTo pearson;

	public String getaffiliation(){
		return affiliation;
	}

	public String getcontactPoint(){
		return contactPoint;
	}

	public int getId(){
		return id;
	}

	public String getindentifier(){
		return indentifier;
	}

	public PearsonTo getPearson(){
		return pearson;
	}

	/**
	 * 
	 * @param affiliation
	 */
	public void setaffiliation(String affiliation){
		this.affiliation = affiliation;
	}

	/**
	 * 
	 * @param contactpoint
	 */
	public void setcontactPoint(String contactpoint){
		this.contactPoint = contactpoint;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param indentifier
	 */
	public void setindentifier(String indentifier){
		this.indentifier = indentifier;
	}

	/**
	 * 
	 * @param pearson
	 */
	public void setPearson(PearsonTo pearson){
		this.pearson =pearson;
	}

}