///////////////////////////////////////////////////////////
//  InstanceTo.java
//  Macromedia ActionScript Implementation of the Class InstanceTo
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:19:51 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:19:51 AM
 */
@Getter @Setter
public class InstanceTo implements Serializable {

	private static final long serialVersionUID = -237691044;
	private int id;
	private String name;
	private String server;
	private String port;
	private String notes;
	private Set<AuditLogsTo> auditlogss;
	private TenantTo tenant;
	private Set<DomainInstanceTo> domaininstances;

	@Override
	public String toString(){
		return "InstanceTo []";
	}

}