///////////////////////////////////////////////////////////
//  LanguageTo.java
//  Macromedia ActionScript Implementation of the Class LanguageTo
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:43:52 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:43:52 PM
 */
@Getter @Setter
public class LanguageTo implements Serializable {

	private static final long serialVersionUID = -361203552;
	private int id;
	private String name;
	private String codeISO;
	private String isbase;
	private Set<TranslationTo> translations;
	private Set<PersonTo> persons;

	@Override
	public String toString(){
		return "LanguageTo []";
	}

}