///////////////////////////////////////////////////////////
//  MarkerSynonymTo.java
//  Macromedia ActionScript Implementation of the Class MarkerSynonymTo
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:42:43 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:42:43 AM
 */
public class MarkerSynonymTo implements Serializable {

	private static final long serialVersionUID = -120431467;
	private int id;
	private int tenant;
	private Integer synonym;
	MarkerTo marker;

	public int getId(){
		return id;
	}

	public MarkerTo getmarker(){
		return marker;
	}

	public Integer getsynonym(){
		return synonym;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param marker
	 */
	public void setmarker(MarkerTo marker){
		this.marker =marker;
	}

	/**
	 * 
	 * @param synonym
	 */
	public void setsynonym(Integer synonym){
		this.synonym = synonym;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	@Override
	public String toString(){
		return "MarkerSynonymTo []";
	}

}