///////////////////////////////////////////////////////////
//  MarkerTo.java
//  Macromedia ActionScript Implementation of the Class MarkerTo
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:42:44 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:42:44 AM
 */
public class MarkerTo implements Serializable {

	private static final long serialVersionUID = -19788685;
	private int id;
	private int tenant;
	private String name;
	private String description;
	Set<MarkerSynonymTo> markersynonyms;
	AssayGeneTo assaygene;
	Set<VendorTo> vendor;

	public AssayGeneTo getassaygene(){
		return assaygene;
	}

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public Set<MarkerSynonymTo> getmarkersynonyms(){
		return markersynonyms;
	}

	public String getname(){
		return name;
	}

	public int getTenant(){
		return tenant;
	}

	public Set<VendorTo> getvendor(){
		return vendor;
	}

	/**
	 * 
	 * @param assaygene
	 */
	public void setassaygene(AssayGeneTo assaygene){
		this.assaygene =assaygene;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param markersynonym
	 */
	public void setmarkersynonyms(Set<MarkerSynonymTo> markersynonym){
		this.markersynonyms =markersynonym;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param vendor
	 */
	public void setvendor(Set<VendorTo> vendor){
		this.vendor =vendor;
	}

	@Override
	public String toString(){
		return "MarkerTo []";
	}

}