///////////////////////////////////////////////////////////
//  MessageTo.java
//  Macromedia ActionScript Implementation of the Class MessageTo
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:35 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:35 AM
 */
@Getter @Setter
public class MessageTo implements Serializable {

	private static final long serialVersionUID = 156689974;
	private int id;
	private String description;
	private String sql;
	private String filterClause;
	private HtmlTagTo htmltag;

	@Override
	public String toString(){
		return "MessageTo []";
	}

}