///////////////////////////////////////////////////////////
//  MessageTo.java
//  Macromedia ActionScript Implementation of the Class MessageTo
//  Generated by Enterprise Architect
//  Created on:      27-Apr-2020 9:47:43 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import org.ebs.model.TranslationModel;
import org.ebs.model.ComponentModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Apr-2020 9:47:43 AM
 */
public class MessageTo implements Serializable {

	ComponentTo component;
	private String Description;
	private String filterClause;
	private int id;
	private static final long serialVersionUID = 159136888;
	private String sql;
	Set<TranslationTo> Translations;

	public ComponentTo getComponent(){
		 return component;
	}

	public String getDescription(){
		return Description;
	}

	public String getfilterClause(){
		return filterClause;
	}

	public int getId(){
		return id;
	}

	public String getsql(){
		return sql;
	}

	public Set<TranslationTo> getTranslations(){
		return Translations;
	}

	/**
	 * 
	 * @param component
	 */
	public void setComponent(ComponentTo component){
		this.component = component;
	}

	/**
	 * 
	 * @param description
	 */
	public void setDescription(String description){
		this.Description = description;
	}

	/**
	 * 
	 * @param filterclause
	 */
	public void setfilterClause(String filterclause){
		this.filterClause = filterclause;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param sql
	 */
	public void setsql(String sql){
		this.sql = sql;
	}

	/**
	 * 
	 * @param translation
	 */
	public void setTranslations(Set<TranslationTo> translation){
		this.Translations =translation;
	}

}