///////////////////////////////////////////////////////////
//  PartnerTo.java
//  Macromedia ActionScript Implementation of the Class PartnerTo
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:50 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:50 PM
 */
public class PartnerTo implements Serializable {

	private static final long serialVersionUID = 208264347;
	private int id;
	private int tenant_id;
	private String affiliation;
	private String contactPoint;
	private String indentifier;
	PersonTo person;

	public String getaffiliation(){
		return affiliation;
	}

	public String getcontactPoint(){
		return contactPoint;
	}

	public int getId(){
		return id;
	}

	public String getindentifier(){
		return indentifier;
	}

	public PersonTo getPerson(){
		return person;
	}

	public int getTenantId(){
		return tenant_id;
	}

	/**
	 * 
	 * @param affiliation
	 */
	public void setaffiliation(String affiliation){
		this.affiliation = affiliation;
	}

	/**
	 * 
	 * @param contactpoint
	 */
	public void setcontactPoint(String contactpoint){
		this.contactPoint = contactpoint;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param indentifier
	 */
	public void setindentifier(String indentifier){
		this.indentifier = indentifier;
	}

	/**
	 * 
	 * @param person
	 */
	public void setPerson(PersonTo person){
		this.person =person;
	}

	/**
	 * 
	 * @param id
	 */
	public void setTenantId(int id){
		this.tenant_id=id;
	}

}