///////////////////////////////////////////////////////////
//  PermissionTo.java
//  Macromedia ActionScript Implementation of the Class PermissionTo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:13:56 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:13:56 PM
 */
public class PermissionTo implements Serializable {

	private static final long serialVersionUID = -54042310;
	private int id;
	private int tenant;
	RoleActionTo roleaction;

	public int getId(){
		return id;
	}

	public RoleActionTo getRoleAction(){
		return roleaction;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param roleaction
	 */
	public void setRoleAction(RoleActionTo roleaction){
		this.roleaction =roleaction;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	@Override
	public String toString(){
		return "PermissionTo []";
	}

}