///////////////////////////////////////////////////////////
//  PersonStatusTo.java
//  Macromedia ActionScript Implementation of the Class PersonStatusTo
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:46 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:46 AM
 */
@Getter @Setter
public class PersonStatusTo implements Serializable {

	private static final long serialVersionUID = 458474995;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private Set<PersonTo> persons;

	@Override
	public String toString(){
		return "PersonStatusTo []";
	}

}