///////////////////////////////////////////////////////////
//  PhaseTo.java
//  Macromedia ActionScript Implementation of the Class PhaseTo
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:47 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:47 AM
 */
@Getter @Setter
public class PhaseTo implements Serializable {

	private static final long serialVersionUID = -166797829;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private String help;
	private int sequence;
	private Set<StageTo> stages;
	private WorkflowTo workflow;
	private HtmlTagTo htmltag;

	@Override
	public String toString(){
		return "PhaseTo [sequence=" + sequence + ",]";
	}

}