///////////////////////////////////////////////////////////
//  ProductFunctionTo.java
//  Macromedia ActionScript Implementation of the Class ProductFunctionTo
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:19:58 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.util.Set;
import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:19:58 AM
 */
@Getter @Setter
public class ProductFunctionTo implements Serializable {

	private static final long serialVersionUID = 150723003;
	private int id;
	private String description;
	private boolean systemType;
	private String action;
	private Set<RoleTo> roles;
	private ProductTo product;

	@Override
	public String toString(){
		return "ProductFunctionTo [systemType=" + systemType + ",]";
	}

}