///////////////////////////////////////////////////////////
//  ProgramTo.java
//  Macromedia ActionScript Implementation of the Class ProgramTo
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:44:18 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:44:18 PM
 */
@Getter @Setter
public class ProgramTo implements Serializable {

	private static final long serialVersionUID = 41308308;
	private int id;
	private String programcode;
	private String programname;
	private String programtype;
	private String programstatus;
	private String description;
	private Set<ProjectTo> projects;
	private TenantTo tenant;
	private Set<TeamTo> teams;
	private CropTo crop;

	@Override
	public String toString(){
		return "ProgramTo []";
	}

}