///////////////////////////////////////////////////////////
//  RequestTo.java
//  Macromedia ActionScript Implementation of the Class RequestTo
//  Generated by Enterprise Architect
//  Created on:      23-Jul-2020 10:47:03 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 23-Jul-2020 10:47:03 PM
 */
public class RequestTo implements Serializable {

	private static final long serialVersionUID = -337449728;
	private int id;
	private int tenant;
	private String requester;
	private Date submition_date;
	private String admin_contact;
	private String charge_account;
	private String description;
	PurposeTo purpose;
	Set<WorkflowCFValueTo> workflowcfvalues;
	WorkflowInstanceTo workflowinstance;

	public String getadmin_contact(){
		return admin_contact;
	}

	public String getcharge_account(){
		return charge_account;
	}

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public PurposeTo getpurpose(){
		return purpose;
	}

	public String getrequester(){
		return requester;
	}

	public Date getsubmition_date(){
		return submition_date;
	}

	public int getTenant(){
		return tenant;
	}

	public Set<WorkflowCFValueTo> getworkflowcfvalues(){
		return workflowcfvalues;
	}

	public WorkflowInstanceTo getworkflowinstance(){
		return workflowinstance;
	}

	/**
	 * 
	 * @param admin_contact
	 */
	public void setadmin_contact(String admin_contact){
		this.admin_contact = admin_contact;
	}

	/**
	 * 
	 * @param charge_account
	 */
	public void setcharge_account(String charge_account){
		this.charge_account = charge_account;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param purpose
	 */
	public void setpurpose(PurposeTo purpose){
		this.purpose =purpose;
	}

	/**
	 * 
	 * @param requester
	 */
	public void setrequester(String requester){
		this.requester = requester;
	}

	/**
	 * 
	 * @param submition_date
	 */
	public void setsubmition_date(Date submition_date){
		this.submition_date = submition_date;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param workflowcfvalue
	 */
	public void setworkflowcfvalues(Set<WorkflowCFValueTo> workflowcfvalue){
		this.workflowcfvalues =workflowcfvalue;
	}

	/**
	 * 
	 * @param workflowinstance
	 */
	public void setworkflowinstance(WorkflowInstanceTo workflowinstance){
		this.workflowinstance =workflowinstance;
	}

	@Override
	public String toString(){
		return "RequestTo []";
	}

}