///////////////////////////////////////////////////////////
//  RoleActionTo.java
//  Macromedia ActionScript Implementation of the Class RoleActionTo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:14:18 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:14:18 PM
 */
public class RoleActionTo implements Serializable {

	private static final long serialVersionUID = 453631996;
	private int id;
	private int tenant;
	private int allow;
	ActionTo action;
	Set<PermissionTo> permissions;
	RoleTo role;

	public ActionTo getAction(){
		return action;
	}

	public int getallow(){
		return allow;
	}

	public int getId(){
		return id;
	}

	public Set<PermissionTo> getPermissions(){
		return permissions;
	}

	public RoleTo getRole(){
		return role;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param action
	 */
	public void setAction(ActionTo action){
		this.action =action;
	}

	/**
	 * 
	 * @param allow
	 */
	public void setallow(int allow){
		this.allow = allow;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param permission
	 */
	public void setPermissions(Set<PermissionTo> permission){
		this.permissions =permission;
	}

	/**
	 * 
	 * @param role
	 */
	public void setRole(RoleTo role){
		this.role =role;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	@Override
	public String toString(){
		return "RoleActionTo [allow=" + allow + ",]";
	}

}