///////////////////////////////////////////////////////////
//  RoleTo.java
//  Macromedia ActionScript Implementation of the Class RoleTo
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:05:56 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:05:56 AM
 */
@Getter @Setter
public class RoleTo implements Serializable {

	private static final long serialVersionUID = -261302415;
	private int id;
	private int tenant;
	private String description;
	private String securitygroup;
	private Set<RoleActionTo> roleactions;
	private Set<ActionTo> actions;
	private Set<UserTo> users;

	@Override
	public String toString(){
		return "RoleTo []";
	}

}