///////////////////////////////////////////////////////////
//  RoleTo.java
//  Macromedia ActionScript Implementation of the Class RoleTo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:14:20 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:14:20 PM
 */
public class RoleTo implements Serializable {

	private static final long serialVersionUID = -54497074;
	private int id;
	private int tenant;
	private String description;
	private String securityGroup;
	Set<RoleActionTo> roleactions;
	Set<UserTo> user;

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public Set<RoleActionTo> getRoleActions(){
		return roleactions;
	}

	public String getsecurityGroup(){
		return securityGroup;
	}

	public int getTenant(){
		return tenant;
	}

	public Set<UserTo> getUser(){
		return user;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param roleaction
	 */
	public void setRoleActions(Set<RoleActionTo> roleaction){
		this.roleactions =roleaction;
	}

	/**
	 * 
	 * @param securitygroup
	 */
	public void setsecurityGroup(String securitygroup){
		this.securityGroup = securitygroup;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param user
	 */
	public void setUser(Set<UserTo> user){
		this.user =user;
	}

	@Override
	public String toString(){
		return "RoleTo []";
	}

}