///////////////////////////////////////////////////////////
//  SessionTo.java
//  Macromedia ActionScript Implementation of the Class SessionTo
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:43:34 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:43:34 AM
 */
public class SessionTo implements Serializable {

	private static final long serialVersionUID = 382411736;
	private int id;
	private int tenant;
	private String webSession;
	private String remote_Address;
	private String remote_host;
	UserTo user;
	InstanceTo instance;

	public int getId(){
		return id;
	}

	public InstanceTo getinstance(){
		return instance;
	}

	public String getremote_Address(){
		return remote_Address;
	}

	public String getremote_host(){
		return remote_host;
	}

	public int getTenant(){
		return tenant;
	}

	public UserTo getuser(){
		return user;
	}

	public String getwebSession(){
		return webSession;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param instance
	 */
	public void setinstance(InstanceTo instance){
		this.instance =instance;
	}

	/**
	 * 
	 * @param remote_address
	 */
	public void setremote_Address(String remote_address){
		this.remote_Address = remote_address;
	}

	/**
	 * 
	 * @param remote_host
	 */
	public void setremote_host(String remote_host){
		this.remote_host = remote_host;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param user
	 */
	public void setuser(UserTo user){
		this.user =user;
	}

	/**
	 * 
	 * @param websession
	 */
	public void setwebSession(String websession){
		this.webSession = websession;
	}

	@Override
	public String toString(){
		return "SessionTo []";
	}

}