///////////////////////////////////////////////////////////
//  StyleThemeTo.java
//  Macromedia ActionScript Implementation of the Class StyleThemeTo
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:23 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import org.ebs.model.PreferenceModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:23 PM
 */
public class StyleThemeTo implements Serializable {

	private static final long serialVersionUID = -419560360;
	private int id;
	private int tenant_id;
	private String description;
	private String path;
	private String physicalName;
	private Boolean isDefault;
	Set<PreferenceTo> preferences;

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public Boolean getisDefault(){
		return isDefault;
	}

	public String getpath(){
		return path;
	}

	public String getphysicalName(){
		return physicalName;
	}

	public Set<PreferenceTo> getPreferences(){
		return preferences;
	}

	public int getTenantId(){
		return tenant_id;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param isdefault
	 */
	public void setisDefault(Boolean isdefault){
		this.isDefault = isdefault;
	}

	/**
	 * 
	 * @param path
	 */
	public void setpath(String path){
		this.path = path;
	}

	/**
	 * 
	 * @param physicalname
	 */
	public void setphysicalName(String physicalname){
		this.physicalName = physicalname;
	}

	/**
	 * 
	 * @param preference
	 */
	public void setPreferences(Set<PreferenceTo> preference){
		this.preferences =preference;
	}

	/**
	 * 
	 * @param id
	 */
	public void setTenantId(int id){
		this.tenant_id=id;
	}

}