///////////////////////////////////////////////////////////
//  TechnologyPlatformTo.java
//  Macromedia ActionScript Implementation of the Class TechnologyPlatformTo
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:18 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:18 AM
 */
@Getter @Setter
public class TechnologyPlatformTo implements Serializable {

	private static final long serialVersionUID = -104645624;
	private int id;
	private int tenant;
	private String name;
	private String description;
	private Set<AssayclassTo> assayclasss;
	private Set<VendorTo> vendors;

	@Override
	public String toString(){
		return "TechnologyPlatformTo []";
	}

}