///////////////////////////////////////////////////////////
//  WorkflowInstanceTo.java
//  Macromedia ActionScript Implementation of the Class WorkflowInstanceTo
//  Generated by Enterprise Architect
//  Created on:      23-Jul-2020 10:47:35 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.to;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 23-Jul-2020 10:47:35 PM
 */
public class WorkflowInstanceTo implements Serializable {

	private static final long serialVersionUID = 28306727;
	private int id;
	private int tenant;
	private Date complete;
	private Date initiated;
	Set<WorkflowStatusTo> workflowstatuss;
	Set<WorkflowEventTo> workflowevents;
	WorkflowTo workflow;
	Set<RequestTo> requests;

	public Date getcomplete(){
		return complete;
	}

	public int getId(){
		return id;
	}

	public Date getinitiated(){
		return initiated;
	}

	public Set<RequestTo> getrequests(){
		return requests;
	}

	public int getTenant(){
		return tenant;
	}

	public WorkflowTo getworkflow(){
		return workflow;
	}

	public Set<WorkflowEventTo> getworkflowevents(){
		return workflowevents;
	}

	public Set<WorkflowStatusTo> getworkflowstatuss(){
		return workflowstatuss;
	}

	/**
	 * 
	 * @param complete
	 */
	public void setcomplete(Date complete){
		this.complete = complete;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id=id;
	}

	/**
	 * 
	 * @param initiated
	 */
	public void setinitiated(Date initiated){
		this.initiated = initiated;
	}

	/**
	 * 
	 * @param request
	 */
	public void setrequests(Set<RequestTo> request){
		this.requests =request;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param workflow
	 */
	public void setworkflow(WorkflowTo workflow){
		this.workflow =workflow;
	}

	/**
	 * 
	 * @param workflowevent
	 */
	public void setworkflowevents(Set<WorkflowEventTo> workflowevent){
		this.workflowevents =workflowevent;
	}

	/**
	 * 
	 * @param workflowstatus
	 */
	public void setworkflowstatuss(Set<WorkflowStatusTo> workflowstatus){
		this.workflowstatuss =workflowstatus;
	}

	@Override
	public String toString(){
		return "WorkflowInstanceTo []";
	}

}