///////////////////////////////////////////////////////////
//  AuditLogsModel.java
//  Macromedia ActionScript Implementation of the Class AuditLogsModel
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:20 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ebs.util.Auditable;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:20 PM
 */
@Entity @Table(name="AuditLogs",schema="tenant")
public class AuditLogsModel extends Auditable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tenant_id;
	@Column(name="correlationId")
	private String correlationId;
	@Column(name="message")
	private String message;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@ManyToOne(fetch=FetchType.EAGER, optional =false) @JoinColumn(name="instance_id")
	InstanceModel instance;

	public String getcorrelationId(){
		return correlationId;
	}

	public int getId(){
		return id;
	}

	public InstanceModel getInstance(){
		return instance;
	}

	public String getmessage(){
		return message;
	}

	public int getTenantId(){
		return tenant_id;
	}

	/**
	 * 
	 * @param correlationid
	 */
	public void setcorrelationId(String correlationid){
		this.correlationId = correlationid;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id = id;
	}

	/**
	 * 
	 * @param instance
	 */
	public void setInstance(InstanceModel instance){
		this.instance =instance;
	}

	/**
	 * 
	 * @param message
	 */
	public void setmessage(String message){
		this.message = message;
	}

	/**
	 * 
	 * @param id
	 */
	public void setTenantId(int id){
		this.tenant_id=id;
	}

}