///////////////////////////////////////////////////////////
//  DelegationModel.java
//  Macromedia ActionScript Implementation of the Class DelegationModel
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:42:26 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:42:26 AM
 */
@Entity @Table(name="Delegation",schema="tenant")
public class DelegationModel extends Auditable {

	private static final long serialVersionUID = -451536017;
	@Column(name="tenant_id")
	private int tenant;
	@Column(name="startDate")
	private Date startDate;
	@Column(name="endDate")
	private Date endDate;
	@Column(name="DelegateTo")
	private String DelegateTo;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="user_id")
	UserModel user;

	public String getDelegateTo(){
		return DelegateTo;
	}

	public Date getendDate(){
		return endDate;
	}

	public int getId(){
		return id;
	}

	public Date getstartDate(){
		return startDate;
	}

	public int getTenant(){
		return tenant;
	}

	public UserModel getuser(){
		return user;
	}

	/**
	 * 
	 * @param delegateto
	 */
	public void setDelegateTo(String delegateto){
		this.DelegateTo = delegateto;
	}

	/**
	 * 
	 * @param enddate
	 */
	public void setendDate(Date enddate){
		this.endDate = enddate;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id = id;
	}

	/**
	 * 
	 * @param startdate
	 */
	public void setstartDate(Date startdate){
		this.startDate = startdate;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param user
	 */
	public void setuser(UserModel user){
		this.user =user;
	}

	@Override
	public String toString(){
		return "DelegationModel [id=" + id + ",]";
	}

}