///////////////////////////////////////////////////////////
//  MarkerModel.java
//  Macromedia ActionScript Implementation of the Class MarkerModel
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 12:19:25 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import javax.persistence.ManyToMany;
import lombok.Getter;
import lombok.Setter;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 12:19:25 AM
 */
@Entity @Table(name="Marker",schema="analyticalsampling") @Getter @Setter
public class MarkerModel extends Auditable {

	private static final long serialVersionUID = -173557309;
	@Column(name="tenant_id")
	private int tenant;
	@Column(name="name")
	private String name;
	@Column(name="description")
	private String description;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@OneToMany(mappedBy = "marker",fetch=FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<MarkerSynonymModel> markersynonyms;
	@ManyToOne(fetch=FetchType.LAZY, optional =false) @JoinColumn(name="assaygene_id")
	private AssayGeneModel assaygene;
	@ManyToMany(mappedBy="markers")
	private Set<VendorModel> vendors;

	@Override
	public String toString(){
		return "MarkerModel [id=" + id + ",]";
	}

}