///////////////////////////////////////////////////////////
//  NumberSequenceRuleSegmentModel.java
//  Macromedia ActionScript Implementation of the Class NumberSequenceRuleSegmentModel
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:19:53 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import lombok.Getter;
import lombok.Setter;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:19:53 AM
 */
@Entity @Table(name="number_sequence_rule_segment",schema="core") @Getter @Setter
public class NumberSequenceRuleSegmentModel extends Auditable {

	private static final long serialVersionUID = 468249297;
	@Column(name="tenant_id")
	private int tenant;
	@Column(name="length")
	private int length;
	@Column(name="custom_field")
	private String customField;
	@Column(name="position")
	private int position;
	@Column(name="formula")
	private String formula;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@ManyToOne(fetch=FetchType.LAZY, optional =false) @JoinColumn(name="segment_id")
	private SegmentModel segment;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="numbersequencerule_id")
	private NumberSequenceRuleModel numbersequencerule;

	@Override
	public String toString(){
		return "NumberSequenceRuleSegmentModel [length=" + length + ",position=" + position + ",id=" + id + ",]";
	}

}