///////////////////////////////////////////////////////////
//  PreferenceModel.java
//  Macromedia ActionScript Implementation of the Class PreferenceModel
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:48 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import lombok.Getter;
import lombok.Setter;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:48 AM
 */
@Entity @Table(name="Preference",schema="core") @Getter @Setter
public class PreferenceModel extends Auditable {

	private static final long serialVersionUID = 224485918;
	@Column(name="tenant_id")
	private int tenant;
	@Column(name="comment")
	private String comment;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="user_id")
	private UserModel user;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="alert_id")
	private AlertModel alert;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="styletheme_id")
	private StyleThemeModel styletheme;

	@Override
	public String toString(){
		return "PreferenceModel [id=" + id + ",]";
	}

}