///////////////////////////////////////////////////////////
//  RoleActionModel.java
//  Macromedia ActionScript Implementation of the Class RoleActionModel
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:43:19 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:43:19 AM
 */
@Entity @Table(name="RoleAction",schema="tenant")
public class RoleActionModel extends Auditable {

	private static final long serialVersionUID = 355910249;
	@Column(name="tenant_id")
	private int tenant;
	@Column(name="allow")
	private int allow;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="action_id")
	ActionModel action;
	@OneToMany(mappedBy = "roleaction",fetch=FetchType.LAZY, cascade = CascadeType.ALL)
	Set<PermissionModel> permissions;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="role_id")
	RoleModel role;

	public ActionModel getaction(){
		return action;
	}

	public int getallow(){
		return allow;
	}

	public int getId(){
		return id;
	}

	public Set<PermissionModel> getpermissions(){
		return permissions;
	}

	public RoleModel getrole(){
		return role;
	}

	public int getTenant(){
		return tenant;
	}

	/**
	 * 
	 * @param action
	 */
	public void setaction(ActionModel action){
		this.action =action;
	}

	/**
	 * 
	 * @param allow
	 */
	public void setallow(int allow){
		this.allow = allow;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id = id;
	}

	/**
	 * 
	 * @param permission
	 */
	public void setpermissions(Set<PermissionModel> permission){
		this.permissions =permission;
	}

	/**
	 * 
	 * @param role
	 */
	public void setrole(RoleModel role){
		this.role =role;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	@Override
	public String toString(){
		return "RoleActionModel [allow=" + allow + ",id=" + id + ",]";
	}

}