///////////////////////////////////////////////////////////
//  SessionModel.java
//  Macromedia ActionScript Implementation of the Class SessionModel
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:19 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import javax.persistence.ManyToMany;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Set;
import java.util.Date;
import java.util.UUID;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:19 PM
 */
@Entity @Table(name="Session",schema="tenant")
public class SessionModel extends Auditable {

	private int tenant_id;
	@Column(name="webSession")
	private String webSession;
	@Column(name="remote_Address")
	private String remote_Address;
	@Column(name="remote_host")
	private String remote_host;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="user_id")
	UserModel user;
	@ManyToOne(fetch=FetchType.LAZY, optional =true) @JoinColumn(name="instance_id")
	InstanceModel instance;

	public int getId(){
		return id;
	}

	public InstanceModel getInstance(){
		return instance;
	}

	public String getremote_Address(){
		return remote_Address;
	}

	public String getremote_host(){
		return remote_host;
	}

	public int getTenantId(){
		return tenant_id;
	}

	public UserModel getUser(){
		return user;
	}

	public String getwebSession(){
		return webSession;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id = id;
	}

	/**
	 * 
	 * @param instance
	 */
	public void setInstance(InstanceModel instance){
		this.instance =instance;
	}

	/**
	 * 
	 * @param remote_address
	 */
	public void setremote_Address(String remote_address){
		this.remote_Address = remote_address;
	}

	/**
	 * 
	 * @param remote_host
	 */
	public void setremote_host(String remote_host){
		this.remote_host = remote_host;
	}

	/**
	 * 
	 * @param id
	 */
	public void setTenantId(int id){
		this.tenant_id=id;
	}

	/**
	 * 
	 * @param user
	 */
	public void setUser(UserModel user){
		this.user =user;
	}

	/**
	 * 
	 * @param websession
	 */
	public void setwebSession(String websession){
		this.webSession = websession;
	}

}