///////////////////////////////////////////////////////////
//  TenantModel.java
//  Macromedia ActionScript Implementation of the Class TenantModel
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:28 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import java.util.UUID;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import org.ebs.util.Auditable;
import javax.persistence.ManyToMany;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Set;
import java.util.Date;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:28 PM
 */
@Entity @Table(name="Tenant",schema="tnt")
public class TenantModel extends Auditable {

	@Column(name="name")
	private String name;
	@Column(name="expiration")
	private Date expiration;
	@Column(name="expire")
	private boolean expire;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@OneToMany(mappedBy = "tenant",fetch=FetchType.EAGER, cascade = CascadeType.ALL)
	Set<UserModel> users;
	@OneToMany(mappedBy = "tenant",fetch=FetchType.EAGER, cascade = CascadeType.ALL)
	Set<InstanceModel> instances;
	@OneToMany(mappedBy = "tenant",fetch=FetchType.EAGER, cascade = CascadeType.ALL)
	Set<WorkflowModel> workflows;
	@ManyToOne(fetch=FetchType.EAGER, optional =false) @JoinColumn(name="organization_id")
	OrganizationModel organization;
	@ManyToOne(fetch=FetchType.EAGER, optional =false) @JoinColumn(name="authenticationtype_id")
	AuthenticationTypeModel authenticationtype;
	@ManyToOne(fetch=FetchType.EAGER, optional =false) @JoinColumn(name="customer_id")
	CustomerModel customer;
	@OneToMany(mappedBy = "tenant",fetch=FetchType.EAGER, cascade = CascadeType.ALL)
	Set<PearsonModel> pearsons;

	public AuthenticationTypeModel getAuthenticationType(){
		return authenticationtype;
	}

	public CustomerModel getCustomer(){
		return customer;
	}

	public Date getexpiration(){
		return expiration;
	}

	public boolean getexpire(){
		return expire;
	}

	public int getId(){
		return id;
	}

	public Set<InstanceModel> getInstances(){
		return instances;
	}

	public String getname(){
		return name;
	}

	public OrganizationModel getOrganization(){
		return organization;
	}

	public Set<PearsonModel> getPearsons(){
		return pearsons;
	}

	public Set<UserModel> getUsers(){
		return users;
	}

	public Set<WorkflowModel> getWorkflows(){
		return workflows;
	}

	/**
	 * 
	 * @param authenticationtype
	 */
	public void setAuthenticationType(AuthenticationTypeModel authenticationtype){
		this.authenticationtype =authenticationtype;
	}

	/**
	 * 
	 * @param customer
	 */
	public void setCustomer(CustomerModel customer){
		this.customer =customer;
	}

	/**
	 * 
	 * @param expiration
	 */
	public void setexpiration(Date expiration){
		this.expiration = expiration;
	}

	/**
	 * 
	 * @param expire
	 */
	public void setexpire(boolean expire){
		this.expire = expire;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id = id;
	}

	/**
	 * 
	 * @param instance
	 */
	public void setInstances(Set<InstanceModel> instance){
		this.instances =instance;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param organization
	 */
	public void setOrganization(OrganizationModel organization){
		this.organization =organization;
	}

	/**
	 * 
	 * @param pearson
	 */
	public void setPearsons(Set<PearsonModel> pearson){
		this.pearsons =pearson;
	}

	/**
	 * 
	 * @param user
	 */
	public void setUsers(Set<UserModel> user){
		this.users =user;
	}

	/**
	 * 
	 * @param workflow
	 */
	public void setWorkflows(Set<WorkflowModel> workflow){
		this.workflows =workflow;
	}

}