///////////////////////////////////////////////////////////
//  TraitClassModel.java
//  Macromedia ActionScript Implementation of the Class TraitClassModel
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:43:41 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import javax.persistence.FetchType;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:43:41 AM
 */
@Entity @Table(name="TraitClass",schema="analyticalsampling")
public class TraitClassModel extends Auditable {

	private static final long serialVersionUID = 206238705;
	@Column(name="tenant_id")
	private int tenant;
	@Column(name="name")
	private String name;
	@Column(name="description")
	private String description;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@OneToMany(mappedBy = "traitclass",fetch=FetchType.LAZY, cascade = CascadeType.ALL)
	Set<TraitModel> traits;

	public String getdescription(){
		return description;
	}

	public int getId(){
		return id;
	}

	public String getname(){
		return name;
	}

	public int getTenant(){
		return tenant;
	}

	public Set<TraitModel> gettraits(){
		return traits;
	}

	/**
	 * 
	 * @param description
	 */
	public void setdescription(String description){
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(int id){
		this.id = id;
	}

	/**
	 * 
	 * @param name
	 */
	public void setname(String name){
		this.name = name;
	}

	/**
	 * 
	 * @param tenantid
	 */
	public void setTenant(int tenantid){
		this.tenant=tenantid;
	}

	/**
	 * 
	 * @param trait
	 */
	public void settraits(Set<TraitModel> trait){
		this.traits =trait;
	}

	@Override
	public String toString(){
		return "TraitClassModel [id=" + id + ",]";
	}

}