///////////////////////////////////////////////////////////
//  WorkflowInstanceModel.java
//  Macromedia ActionScript Implementation of the Class WorkflowInstanceModel
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:06:35 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model;

import org.ebs.util.Auditable;
import lombok.Getter;
import lombok.Setter;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import java.util.Set;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:06:35 AM
 */
@Entity @Table(name="WorkflowInstance",schema="workflow") @Getter @Setter
public class WorkflowInstanceModel extends Auditable {

	private static final long serialVersionUID = 54165662;
	@Column(name="tenant_id")
	private int tenant;
	@Column(name="complete")
	private Date complete;
	@Column(name="initiated")
	private Date initiated;
	@GeneratedValue(strategy= GenerationType.IDENTITY) @Id @Column
	private int id;
	@OneToMany(mappedBy = "workflowinstance",fetch=FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<WorkflowStatusModel> workflowstatuss;
	@OneToMany(mappedBy = "workflowinstance",fetch=FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<WorkflowEventModel> workflowevents;
	@ManyToOne(fetch=FetchType.LAZY, optional =false) @JoinColumn(name="workflow_id")
	private WorkflowModel workflow;
	@OneToMany(mappedBy = "workflowinstance",fetch=FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<RequestModel> requests;

	@Override
	public String toString(){
		return "WorkflowInstanceModel [id=" + id + ",]";
	}

}