///////////////////////////////////////////////////////////
//  AssayclassConverterInput.java
//  Macromedia ActionScript Implementation of the Class AssayclassConverterInput
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:10:51 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.AssayclassModel;
import org.ebs.services.to.Input.AssayclassInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:10:51 AM
 */
@Component
  class AssayclassConverterInput implements Converter<AssayclassInput,AssayclassModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public AssayclassModel convert(AssayclassInput source){
		AssayclassModel target = new  AssayclassModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}