///////////////////////////////////////////////////////////
//  AttributesConverterInput.java
//  Macromedia ActionScript Implementation of the Class AttributesConverterInput
//  Generated by Enterprise Architect
//  Created on:      09-Aug-2020 4:50:15 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.ebs.model.AttributesModel;
import org.ebs.services.to.Input.AttributesInput;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 09-Aug-2020 4:50:15 PM
 */
@Component
  class AttributesConverterInput implements Converter<AttributesInput,AttributesModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public AttributesModel convert(AttributesInput source){
		AttributesModel target = new  AttributesModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}