///////////////////////////////////////////////////////////
//  CustomerConverter.java
//  Macromedia ActionScript Implementation of the Class CustomerConverter
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:04:55 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.ebs.services.to.CustomerTo;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.CustomerModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:04:55 AM
 */
@Component
  class CustomerConverter implements Converter<CustomerModel,CustomerTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public CustomerTo convert(CustomerModel source){
		CustomerTo target = new  CustomerTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}