///////////////////////////////////////////////////////////
//  DelegationConverterInput.java
//  Macromedia ActionScript Implementation of the Class DelegationConverterInput
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2020 11:58:12 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.DelegationModel;
import org.ebs.services.to.Input.DelegationInput;
import org.ebs.services.to.DelegationTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 28-Apr-2020 11:58:12 PM
 */
@Component
public class DelegationConverterInput implements Converter<DelegationInput,DelegationModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public DelegationModel convert(DelegationInput source){
		DelegationModel target = new  DelegationModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}