///////////////////////////////////////////////////////////
//  DomainConverter.java
//  Macromedia ActionScript Implementation of the Class DomainConverter
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:25 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.DomainModel;
import org.ebs.services.to.DomainTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:25 AM
 */
@Component
  class DomainConverter implements Converter<DomainModel,DomainTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public DomainTo convert(DomainModel source){
		DomainTo target = new  DomainTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}