///////////////////////////////////////////////////////////
//  DonorConverterInput.java
//  Macromedia ActionScript Implementation of the Class DonorConverterInput
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:42:28 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.DonorModel;
import org.ebs.services.to.Input.DonorInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:42:28 AM
 */
@Component
  class DonorConverterInput implements Converter<DonorInput,DonorModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public DonorModel convert(DonorInput source){
		DonorModel target = new  DonorModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}