///////////////////////////////////////////////////////////
//  EntityReferenceConverterInput.java
//  Macromedia ActionScript Implementation of the Class EntityReferenceConverterInput
//  Generated by Enterprise Architect
//  Created on:      23-Jul-2020 10:46:24 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.EntityReferenceModel;
import org.ebs.services.to.Input.EntityReferenceInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 23-Jul-2020 10:46:24 PM
 */
@Component
  class EntityReferenceConverterInput implements Converter<EntityReferenceInput,EntityReferenceModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public EntityReferenceModel convert(EntityReferenceInput source){
		EntityReferenceModel target = new  EntityReferenceModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}