///////////////////////////////////////////////////////////
//  InstanceConverterInput.java
//  Macromedia ActionScript Implementation of the Class InstanceConverterInput
//  Generated by Enterprise Architect
//  Created on:      07-Aug-2020 2:59:47 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.InstanceModel;
import org.ebs.services.to.Input.InstanceInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Aug-2020 2:59:47 PM
 */
@Component
  class InstanceConverterInput implements Converter<InstanceInput,InstanceModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public InstanceModel convert(InstanceInput source){
		InstanceModel target = new  InstanceModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}