///////////////////////////////////////////////////////////
//  MarkerSynonymConverter.java
//  Macromedia ActionScript Implementation of the Class MarkerSynonymConverter
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:11:25 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.MarkerSynonymModel;
import org.ebs.services.to.MarkerSynonymTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:11:25 AM
 */
@Component
  class MarkerSynonymConverter implements Converter<MarkerSynonymModel,MarkerSynonymTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public MarkerSynonymTo convert(MarkerSynonymModel source){
		MarkerSynonymTo target = new  MarkerSynonymTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}