///////////////////////////////////////////////////////////
//  PermissionConverterInput.java
//  Macromedia ActionScript Implementation of the Class PermissionConverterInput
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:50 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.ebs.model.PermissionModel;
import org.ebs.services.to.Input.PermissionInput;
import org.springframework.beans.BeanUtils;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:50 PM
 */
@Component
public class PermissionConverterInput implements Converter<PermissionInput,PermissionModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public PermissionModel convert(PermissionInput source){
		PermissionModel target = new  PermissionModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}