///////////////////////////////////////////////////////////
//  PermissionConverter.java
//  Macromedia ActionScript Implementation of the Class PermissionConverter
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:09:50 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.PermissionModel;
import org.ebs.services.to.Input.PermissionInput;
import org.ebs.services.to.PermissionTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:09:50 PM
 */
@Component
public class PermissionConverter implements Converter<PermissionModel,PermissionTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public PermissionTo convert(PermissionModel source){
		PermissionTo target = new  PermissionTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}