///////////////////////////////////////////////////////////
//  PersonStatusConverter.java
//  Macromedia ActionScript Implementation of the Class PersonStatusConverter
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:45 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.PersonStatusModel;
import org.ebs.services.to.PersonStatusTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:45 AM
 */
@Component
  class PersonStatusConverter implements Converter<PersonStatusModel,PersonStatusTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public PersonStatusTo convert(PersonStatusModel source){
		PersonStatusTo target = new  PersonStatusTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}