///////////////////////////////////////////////////////////
//  ProductConverterInput.java
//  Macromedia ActionScript Implementation of the Class ProductConverterInput
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:19:57 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.ProductModel;
import org.ebs.services.to.Input.ProductInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:19:57 AM
 */
@Component
  class ProductConverterInput implements Converter<ProductInput,ProductModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public ProductModel convert(ProductInput source){
		ProductModel target = new  ProductModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}