///////////////////////////////////////////////////////////
//  ServiceTypeConverterInput.java
//  Macromedia ActionScript Implementation of the Class ServiceTypeConverterInput
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:17 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.ebs.model.ServiceTypeModel;
import org.ebs.services.to.Input.ServiceTypeInput;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:17 PM
 */
@Component
public class ServiceTypeConverterInput implements Converter<ServiceTypeInput,ServiceTypeModel> {

	
	private ServiceProviderConverterInput serviceProviderConverterInput;
	private CropConverterInput cropConverterInput; 
	/**
	 * 
	 * @param source
	 */
	@Override
	public ServiceTypeModel convert(ServiceTypeInput source){
		ServiceTypeModel target = new  ServiceTypeModel(); 
		BeanUtils.copyProperties(source, target); 
		target.setServiceProvider(serviceProviderConverterInput.convert(source.getServiceProvider()));
		target.setCrop(cropConverterInput.convert(source.getCrop()));
		return target;
	}

	@Autowired
	public ServiceTypeConverterInput(ServiceProviderConverterInput _serviceProviderConverterInput, CropConverterInput _cropConverterInput ) {
		this.serviceProviderConverterInput = _serviceProviderConverterInput;
		this.cropConverterInput = _cropConverterInput;
		
	}
}