///////////////////////////////////////////////////////////
//  ServiceTypeConverter.java
//  Macromedia ActionScript Implementation of the Class ServiceTypeConverter
//  Generated by Enterprise Architect
//  Created on:      09-Aug-2020 4:51:30 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.ServiceTypeModel;
import org.ebs.services.to.ServiceTypeTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 09-Aug-2020 4:51:30 PM
 */
@Component
  class ServiceTypeConverter implements Converter<ServiceTypeModel,ServiceTypeTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public ServiceTypeTo convert(ServiceTypeModel source){
		ServiceTypeTo target = new  ServiceTypeTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}