///////////////////////////////////////////////////////////
//  SessionConverterInput.java
//  Macromedia ActionScript Implementation of the Class SessionConverterInput
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:44:38 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.ebs.model.SessionModel;
import org.ebs.services.to.Input.SessionInput;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:44:38 PM
 */
@Component
  class SessionConverterInput implements Converter<SessionInput,SessionModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public SessionModel convert(SessionInput source){
		SessionModel target = new  SessionModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}