///////////////////////////////////////////////////////////
//  StageConverterInput.java
//  Macromedia ActionScript Implementation of the Class StageConverterInput
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:54 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.StageModel;
import org.ebs.services.to.Input.StageInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:54 AM
 */
@Component
  class StageConverterInput implements Converter<StageInput,StageModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public StageModel convert(StageInput source){
		StageModel target = new  StageModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}