///////////////////////////////////////////////////////////
//  StatusTypeConverterInput.java
//  Macromedia ActionScript Implementation of the Class StatusTypeConverterInput
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:56 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.StatusTypeModel;
import org.ebs.services.to.Input.StatusTypeInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:56 AM
 */
@Component
  class StatusTypeConverterInput implements Converter<StatusTypeInput,StatusTypeModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public StatusTypeModel convert(StatusTypeInput source){
		StatusTypeModel target = new  StatusTypeModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}