///////////////////////////////////////////////////////////
//  StyleThemeConverterInput.java
//  Macromedia ActionScript Implementation of the Class StyleThemeConverterInput
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:21 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.ebs.model.StyleThemeModel;
import org.ebs.services.to.Input.StyleThemeInput;
import org.springframework.beans.BeanUtils;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:21 PM
 */
@Component
public class StyleThemeConverterInput implements Converter<StyleThemeInput,StyleThemeModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public StyleThemeModel convert(StyleThemeInput source){
		StyleThemeModel target = new  StyleThemeModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}