///////////////////////////////////////////////////////////
//  StyleThemeConverter.java
//  Macromedia ActionScript Implementation of the Class StyleThemeConverter
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:43:34 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.StyleThemeModel;
import org.ebs.services.to.StyleThemeTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:43:34 AM
 */
@Component
  class StyleThemeConverter implements Converter<StyleThemeModel,StyleThemeTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public StyleThemeTo convert(StyleThemeModel source){
		StyleThemeTo target = new  StyleThemeTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}