///////////////////////////////////////////////////////////
//  TeamConverter.java
//  Macromedia ActionScript Implementation of the Class TeamConverter
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:14 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.TeamModel;
import org.ebs.services.to.TeamTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:14 AM
 */
@Component
  class TeamConverter implements Converter<TeamModel,TeamTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public TeamTo convert(TeamModel source){
		TeamTo target = new  TeamTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}