///////////////////////////////////////////////////////////
//  TechnologyPlatformConverter.java
//  Macromedia ActionScript Implementation of the Class TechnologyPlatformConverter
//  Generated by Enterprise Architect
//  Created on:      20-Aug-2020 1:06:39 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.ebs.services.to.TechnologyPlatformTo;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.TechnologyPlatformModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 20-Aug-2020 1:06:39 PM
 */
@Component
  class TechnologyPlatformConverter implements Converter<TechnologyPlatformModel,TechnologyPlatformTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public TechnologyPlatformTo convert(TechnologyPlatformModel source){
		TechnologyPlatformTo target = new  TechnologyPlatformTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}