///////////////////////////////////////////////////////////
//  TenantConverter.java
//  Macromedia ActionScript Implementation of the Class TenantConverter
//  Generated by Enterprise Architect
//  Created on:      27-Apr-2020 9:47:52 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.TenantModel;
import org.ebs.services.to.Input.TenantInput;
import org.ebs.services.to.TenantTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Apr-2020 9:47:52 AM
 */
@Component
public class TenantConverter implements Converter<TenantModel,TenantTo> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public TenantTo convert(TenantModel source){
		TenantTo target = new  TenantTo(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}