///////////////////////////////////////////////////////////
//  TraitConverterInput.java
//  Macromedia ActionScript Implementation of the Class TraitConverterInput
//  Generated by Enterprise Architect
//  Created on:      20-Aug-2020 1:06:45 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.TraitModel;
import org.ebs.services.to.Input.TraitInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 20-Aug-2020 1:06:45 PM
 */
@Component
  class TraitConverterInput implements Converter<TraitInput,TraitModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public TraitModel convert(TraitInput source){
		TraitModel target = new  TraitModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}