///////////////////////////////////////////////////////////
//  TranslationConverterInput.java
//  Macromedia ActionScript Implementation of the Class TranslationConverterInput
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:20:03 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.TranslationModel;
import org.ebs.services.to.Input.TranslationInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:20:03 AM
 */
@Component
  class TranslationConverterInput implements Converter<TranslationInput,TranslationModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public TranslationModel convert(TranslationInput source){
		TranslationModel target = new  TranslationModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}