///////////////////////////////////////////////////////////
//  TypeConverterInput.java
//  Macromedia ActionScript Implementation of the Class TypeConverterInput
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:20:04 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.TypeModel;
import org.ebs.services.to.Input.TypeInput;
import org.springframework.core.convert.converter.Converter;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:20:04 AM
 */
@Component
  class TypeConverterInput implements Converter<TypeInput,TypeModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public TypeModel convert(TypeInput source){
		TypeModel target = new  TypeModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}