///////////////////////////////////////////////////////////
//  WorkflowNodeCFConverterInput.java
//  Macromedia ActionScript Implementation of the Class WorkflowNodeCFConverterInput
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:39 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.services.converter;

import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.beans.BeanUtils;
import org.ebs.model.WorkflowNodeCFModel;
import org.ebs.services.to.Input.WorkflowNodeCFInput;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:39 AM
 */
@Component
  class WorkflowNodeCFConverterInput implements Converter<WorkflowNodeCFInput,WorkflowNodeCFModel> {

	/**
	 * 
	 * @param source
	 */
	@Override
	public WorkflowNodeCFModel convert(WorkflowNodeCFInput source){
		WorkflowNodeCFModel target = new  WorkflowNodeCFModel(); 
		BeanUtils.copyProperties(source, target); 
		return target;
	}

}