///////////////////////////////////////////////////////////
//  ActionResolver.java
//  Macromedia ActionScript Implementation of the Class ActionResolver
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:13:02 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.ActionTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.ActionService;
import org.ebs.services.to.RoleActionTo;
import org.ebs.services.to.ModuleTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:13:02 PM
 */
@Component @Validated
public class ActionResolver implements GraphQLResolver<ActionTo> {

	private ActionService actionService;

	/**
	 * 
	 * @param actionService
	 */
	@Autowired
	public ActionResolver(ActionService actionService){
		this.actionService = actionService; 
	
	}

	/**
	 * 
	 * @param actionTo
	 */
	public ModuleTo getModule(ActionTo actionTo){
		return actionService.findModule(actionTo.getId()).get();
	}

	/**
	 * 
	 * @param action
	 */
	public Set<RoleActionTo> getRoleactions(ActionTo action){
		return actionService.findRoleActions(action.getId());
	}

}