///////////////////////////////////////////////////////////
//  AlertRuleResolver.java
//  Macromedia ActionScript Implementation of the Class AlertRuleResolver
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:10:49 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.AlertRuleTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.ebs.services.AlertRuleService;
import org.ebs.services.to.AlertTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:10:49 AM
 */
@Component @Validated
public class AlertRuleResolver implements GraphQLResolver<AlertRuleTo> {

	private AlertRuleService alertRuleService;

	/**
	 * 
	 * @param alertruleService
	 */
	@Autowired
	public AlertRuleResolver(AlertRuleService alertruleService){
		this.alertRuleService = alertruleService; 
	
	}

	/**
	 * 
	 * @param alertRuleTo
	 */
	public AlertTo getAlert(AlertRuleTo alertRuleTo){
		return alertRuleService.findAlert(alertRuleTo.getId()).get();
	}

}