///////////////////////////////////////////////////////////
//  CountryResolver.java
//  Macromedia ActionScript Implementation of the Class CountryResolver
//  Generated by Enterprise Architect
//  Created on:      13-Jul-2020 5:06:22 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.CountryTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.CountryService;
import org.ebs.services.to.VendorTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Jul-2020 5:06:22 PM
 */
@Component @Validated
public class CountryResolver implements GraphQLResolver<CountryTo> {

	private CountryService countryService;

	/**
	 * 
	 * @param countryService
	 */
	@Autowired
	public CountryResolver(CountryService countryService){
		this.countryService = countryService; 
	
	}

	/**
	 * 
	 * @param country
	 */
	public Set<VendorTo> getVendors(CountryTo country){
		return countryService.findVendors(country.getId());
	}

}