///////////////////////////////////////////////////////////
//  NotificationResolver.java
//  Macromedia ActionScript Implementation of the Class NotificationResolver
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:11:33 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.NotificationTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.ebs.services.NotificationService;
import org.ebs.services.to.HtmlTagTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:11:33 AM
 */
@Component @Validated
public class NotificationResolver implements GraphQLResolver<NotificationTo> {

	private NotificationService notificationService;

	/**
	 * 
	 * @param notificationTo
	 */
	public HtmlTagTo getHtmlTag(NotificationTo notificationTo){
		return notificationService.findHtmlTag(notificationTo.getId()).get();
	}

	/**
	 * 
	 * @param notificationService
	 */
	@Autowired
	public NotificationResolver(NotificationService notificationService){
		this.notificationService = notificationService; 
	
	}

}