///////////////////////////////////////////////////////////
//  PhaseResolver.java
//  Macromedia ActionScript Implementation of the Class PhaseResolver
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:47 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.PhaseTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.PhaseService;
import org.ebs.services.to.StageTo;
import org.ebs.services.to.WorkflowTo;
import org.ebs.services.to.HtmlTagTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:47 AM
 */
@Component @Validated
public class PhaseResolver implements GraphQLResolver<PhaseTo> {

	private PhaseService phaseService;

	/**
	 * 
	 * @param phaseTo
	 */
	public HtmlTagTo getHtmltag(PhaseTo phaseTo){
		return phaseService.findHtmlTag(phaseTo.getId()).get();
	}

	/**
	 * 
	 * @param phase
	 */
	public Set<StageTo> getStages(PhaseTo phase){
		return phaseService.findStages(phase.getId());
	}

	/**
	 * 
	 * @param phaseTo
	 */
	public WorkflowTo getWorkflow(PhaseTo phaseTo){
		return phaseService.findWorkflow(phaseTo.getId()).get();
	}

	/**
	 * 
	 * @param phaseService
	 */
	@Autowired
	public PhaseResolver(PhaseService phaseService){
		this.phaseService = phaseService; 
	
	}

}