///////////////////////////////////////////////////////////
//  ProcessResolver.java
//  Macromedia ActionScript Implementation of the Class ProcessResolver
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:11:47 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.ProcessTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.ProcessService;
import org.ebs.services.to.WorkflowNodeTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:11:47 AM
 */
@Component @Validated
public class ProcessResolver implements GraphQLResolver<ProcessTo> {

	private ProcessService processService;

	/**
	 * 
	 * @param process
	 */
	public Set<WorkflowNodeTo> getWorkflowNodes(ProcessTo process){
		return processService.findWorkflowNodes(process.getId());
	}

	/**
	 * 
	 * @param processService
	 */
	@Autowired
	public ProcessResolver(ProcessService processService){
		this.processService = processService; 
	
	}

}