///////////////////////////////////////////////////////////
//  RoleResolver.java
//  Macromedia ActionScript Implementation of the Class RoleResolver
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 10:44:28 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import org.ebs.services.to.RoleTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.RoleService;
import org.ebs.services.to.RoleActionTo;
import org.ebs.services.to.ActionTo;
import org.ebs.services.to.UserTo;
import com.coxautodev.graphql.tools.GraphQLResolver;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 10:44:28 PM
 */
@Component @Validated
public class RoleResolver implements GraphQLResolver<RoleTo> {

	private RoleService roleService;

	/**
	 * 
	 * @param roleTo
	 */
	public Set<ActionTo> getActions(RoleTo roleTo){
		return roleService.findActions(roleTo.getId());
	}

	/**
	 * 
	 * @param role
	 */
	public Set<RoleActionTo> getRoleactions(RoleTo role){
		return roleService.findRoleActions(role.getId());
	}

	/**
	 * 
	 * @param roleTo
	 */
	public Set<UserTo> getUsers(RoleTo roleTo){
		return roleService.findUsers(roleTo.getId());
	}

	/**
	 * 
	 * @param roleService
	 */
	@Autowired
	public RoleResolver(RoleService roleService){
		this.roleService = roleService; 
	
	}

}