///////////////////////////////////////////////////////////
//  SeasonResolver.java
//  Macromedia ActionScript Implementation of the Class SeasonResolver
//  Generated by Enterprise Architect
//  Created on:      09-Aug-2020 4:51:24 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.SeasonTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.SeasonService;
import org.ebs.services.to.CropTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 09-Aug-2020 4:51:24 PM
 */
@Component @Validated
public class SeasonResolver implements GraphQLResolver<SeasonTo> {

	private SeasonService seasonService;

	/**
	 * 
	 * @param seasonTo
	 */
	public Set<CropTo> getCrops(SeasonTo seasonTo){
		return seasonService.findCrops(seasonTo.getId());
	}

	/**
	 * 
	 * @param seasonService
	 */
	@Autowired
	public SeasonResolver(SeasonService seasonService){
		this.seasonService = seasonService; 
	
	}

}