///////////////////////////////////////////////////////////
//  ServiceProviderResolver.java
//  Macromedia ActionScript Implementation of the Class ServiceProviderResolver
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:06:02 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.ServiceProviderTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.ServiceProviderService;
import org.ebs.services.to.ServiceTypeTo;
import org.ebs.services.to.CountryTo;
import org.ebs.services.to.CropTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:06:02 AM
 */
@Component @Validated
public class ServiceProviderResolver implements GraphQLResolver<ServiceProviderTo> {

	private ServiceProviderService serviceproviderService;

	/**
	 * 
	 * @param serviceproviderTo
	 */
	public CountryTo getCountry(ServiceProviderTo serviceproviderTo){
		return serviceproviderService.findcountry(serviceproviderTo.getId()).get();
	}

	/**
	 * 
	 * @param serviceproviderTo
	 */
	public Set<CropTo> getCrops(ServiceProviderTo serviceproviderTo){
		return serviceproviderService.findcrops(serviceproviderTo.getId());
	}

	/**
	 * 
	 * @param serviceproviderTo
	 */
	public Set<ServiceTypeTo> getServicetypes(ServiceProviderTo serviceproviderTo){
		return serviceproviderService.findservicetypes(serviceproviderTo.getId());
	}

	/**
	 * 
	 * @param serviceproviderService
	 */
	@Autowired
	public ServiceProviderResolver(ServiceProviderService serviceproviderService){
		this.serviceproviderService = serviceproviderService; 
	
	}

}