///////////////////////////////////////////////////////////
//  ServiceProviderResolver.java
//  Macromedia ActionScript Implementation of the Class ServiceProviderResolver
//  Generated by Enterprise Architect
//  Created on:      23-Jul-2020 10:47:10 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.ServiceProviderTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.ebs.services.ServiceProviderService;
import org.ebs.services.to.CountryTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 23-Jul-2020 10:47:10 PM
 */
@Component @Validated
public class ServiceProviderResolver implements GraphQLResolver<ServiceProviderTo> {

	private ServiceProviderService serviceproviderService;

	/**
	 * 
	 * @param serviceproviderTo
	 */
	public CountryTo getCountry(ServiceProviderTo serviceproviderTo){
		return serviceproviderService.findCountry(serviceproviderTo.getId()).get();
	}

	/**
	 * 
	 * @param serviceproviderService
	 */
	@Autowired
	public ServiceProviderResolver(ServiceProviderService serviceproviderService){
		this.serviceproviderService = serviceproviderService; 
	
	}

}