///////////////////////////////////////////////////////////
//  ServiceResolver.java
//  Macromedia ActionScript Implementation of the Class ServiceResolver
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:14:26 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.ServiceTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.ServiceService;
import org.ebs.services.to.AssayclassTo;
import org.ebs.services.to.PurposeTo;
import org.ebs.services.to.RequestTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:14:26 PM
 */
@Component @Validated
public class ServiceResolver implements GraphQLResolver<ServiceTo> {

	private ServiceService serviceService;

	/**
	 * 
	 * @param service
	 */
	public Set<AssayclassTo> getAssayclasss(ServiceTo service){
		return serviceService.findAssayclasss(service.getId());
	}

	/**
	 * 
	 * @param serviceTo
	 */
	public PurposeTo getPurpose(ServiceTo serviceTo){
		return serviceService.findPurpose(serviceTo.getId()).get();
	}

	/**
	 * 
	 * @param service
	 */
	public Set<RequestTo> getRequests(ServiceTo service){
		return serviceService.findRequests(service.getId());
	}

	/**
	 * 
	 * @param serviceService
	 */
	@Autowired
	public ServiceResolver(ServiceService serviceService){
		this.serviceService = serviceService; 
	
	}

}