///////////////////////////////////////////////////////////
//  StyleThemeResolver.java
//  Macromedia ActionScript Implementation of the Class StyleThemeResolver
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 12:20:20 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.StyleThemeTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.StyleThemeService;
import org.ebs.services.to.PreferenceTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 12:20:20 AM
 */
@Component @Validated
public class StyleThemeResolver implements GraphQLResolver<StyleThemeTo> {

	private StyleThemeService stylethemeService;

	/**
	 * 
	 * @param styletheme
	 */
	public Set<PreferenceTo> getPreferences(StyleThemeTo styletheme){
		return stylethemeService.findPreferences(styletheme.getId());
	}

	/**
	 * 
	 * @param stylethemeService
	 */
	@Autowired
	public StyleThemeResolver(StyleThemeService stylethemeService){
		this.stylethemeService = stylethemeService; 
	
	}

}