///////////////////////////////////////////////////////////
//  TraitResolver.java
//  Macromedia ActionScript Implementation of the Class TraitResolver
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:23 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.TraitTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.TraitService;
import org.ebs.services.to.TraitClassTo;
import org.ebs.services.to.AssayGeneTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:23 AM
 */
@Component @Validated
public class TraitResolver implements GraphQLResolver<TraitTo> {

	private TraitService traitService;

	/**
	 * 
	 * @param trait
	 */
	public Set<AssayGeneTo> getAssayGenes(TraitTo trait){
		return traitService.findAssayGenes(trait.getId());
	}

	/**
	 * 
	 * @param traitTo
	 */
	public TraitClassTo getTraitClass(TraitTo traitTo){
		return traitService.findTraitClass(traitTo.getId()).get();
	}

	/**
	 * 
	 * @param traitService
	 */
	@Autowired
	public TraitResolver(TraitService traitService){
		this.traitService = traitService; 
	
	}

}