///////////////////////////////////////////////////////////
//  TypeResolver.java
//  Macromedia ActionScript Implementation of the Class TypeResolver
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:20:04 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.TypeTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import java.util.Set;
import org.ebs.services.TypeService;
import org.ebs.services.to.PersonTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:20:04 AM
 */
@Component @Validated
public class TypeResolver implements GraphQLResolver<TypeTo> {

	private TypeService typeService;

	/**
	 * 
	 * @param typeTo
	 */
	public Set<PersonTo> getPersons(TypeTo typeTo){
		return typeService.findPersons(typeTo.getId());
	}

	/**
	 * 
	 * @param typeService
	 */
	@Autowired
	public TypeResolver(TypeService typeService){
		this.typeService = typeService; 
	
	}

}