///////////////////////////////////////////////////////////
//  WorkflowPhaseResolver.java
//  Macromedia ActionScript Implementation of the Class WorkflowPhaseResolver
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:45 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.graphql.resolvers;

import com.coxautodev.graphql.tools.GraphQLResolver;
import org.ebs.services.to.WorkflowPhaseTo;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;

import lombok.RequiredArgsConstructor;

import java.util.Set;
import org.ebs.services.WorkflowPhaseService;
import org.ebs.services.to.WorkflowStageTo;
import org.ebs.services.to.WorkflowTo;
import org.ebs.services.to.HtmlTagTo;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:45 AM
 */
@Component @Validated
@RequiredArgsConstructor(onConstructor = @__({@Autowired}))
public class WorkflowPhaseResolver implements GraphQLResolver<WorkflowPhaseTo> {

<<<<<<< HEAD
	private WorkflowPhaseService workflowPhaseService;
=======
	private final WorkflowPhaseService workflowphaseService;
>>>>>>> 568e9ead4a84c1e3c26732d642869d5d1811b60f

	/**
	 * 
	 * @param workflowPhaseTo
	 */
<<<<<<< HEAD
	public HtmlTagTo getHtmlTag(WorkflowPhaseTo workflowPhaseTo){
		return workflowPhaseService.findHtmlTag(workflowPhaseTo.getId()).get();
=======
	public HtmlTagTo getHtmltag(WorkflowPhaseTo workflowphaseTo){
		return workflowphaseService.findhtmltag(workflowphaseTo.getId()).orElse(null);
>>>>>>> 568e9ead4a84c1e3c26732d642869d5d1811b60f
	}

	/**
	 * 
	 * @param workflowPhaseTo
	 */
	public WorkflowTo getWorkflow(WorkflowPhaseTo workflowPhaseTo){
		return workflowPhaseService.findWorkflow(workflowPhaseTo.getId()).get();
	}

	/**
	 * 
	 * @param workflowPhase
	 */
	public Set<WorkflowStageTo> getWorkflowStages(WorkflowPhaseTo workflowPhase){
		return workflowPhaseService.findWorkflowStages(workflowPhase.getId());
	}
<<<<<<< HEAD

	/**
	 * 
	 * @param workflowphaseService
	 */
	@Autowired
	public WorkflowPhaseResolver(WorkflowPhaseService workflowphaseService){
		this.workflowPhaseService = workflowphaseService; 
	
	}

=======
>>>>>>> 568e9ead4a84c1e3c26732d642869d5d1811b60f
}