///////////////////////////////////////////////////////////
//  AddressRepository.java
//  Macromedia ActionScript Implementation of the Interface AddressRepository
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:04:32 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.AddressModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:04:32 AM
 */
public interface AddressRepository extends JpaRepository<AddressModel,Integer>, RepositoryExt<AddressModel> {

	/**
	 * 
	 * @param countryId
	 */
	public List<AddressModel> findByCountryId(int countryId);

}