///////////////////////////////////////////////////////////
//  AlertRuleRepository.java
//  Macromedia ActionScript Implementation of the Interface AlertRuleRepository
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:19:42 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.AlertRuleModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:19:42 AM
 */
public interface AlertRuleRepository extends JpaRepository<AlertRuleModel,Integer>, RepositoryExt<AlertRuleModel> {

	/**
	 * 
	 * @param alertId
	 */
	public List<AlertRuleModel> findByAlertId(int alertId);

}