///////////////////////////////////////////////////////////
//  AlertRepository.java
//  Macromedia ActionScript Implementation of the Interface AlertRepository
//  Generated by Enterprise Architect
//  Created on:      07-Aug-2020 2:58:59 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.AlertModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Aug-2020 2:58:59 PM
 */
public interface AlertRepository extends JpaRepository<AlertModel,Integer>, RepositoryExt<AlertModel> {

	/**
	 * 
	 * @param htmltagId
	 */
	public List<AlertModel> findByHtmltagId(int htmltagId);

}