///////////////////////////////////////////////////////////
//  AssayclassRepository.java
//  Macromedia ActionScript Implementation of the Interface AssayclassRepository
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:42:05 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.AssayclassModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:42:05 AM
 */
public interface AssayclassRepository extends JpaRepository<AssayclassModel,Integer>, RepositoryExt<AssayclassModel> {

	/**
	 * 
	 * @param serviceId
	 */
	public List<AssayclassModel> findByServiceId(int serviceId);

}