///////////////////////////////////////////////////////////
//  AttributesRepository.java
//  Macromedia ActionScript Implementation of the Interface AttributesRepository
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:10:55 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.AttributesModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:10:55 AM
 */
public interface AttributesRepository extends JpaRepository<AttributesModel,Integer>, RepositoryExt<AttributesModel> {

	/**
	 * 
	 * @param entityReferenceId
	 */
	public List<AttributesModel> findByEntityReferenceId(int entityReferenceId);

	/**
	 * 
	 * @param htmlTagId
	 */
	public List<AttributesModel> findByHtmlTagId(int htmlTagId);

}