///////////////////////////////////////////////////////////
//  CfTypeRepository.java
//  Macromedia ActionScript Implementation of the Interface CfTypeRepository
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:22 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.CfTypeModel;
import org.ebs.util.RepositoryExt;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:22 AM
 */
public interface CfTypeRepository extends JpaRepository<CfTypeModel,Integer>, RepositoryExt<CfTypeModel> {

}