///////////////////////////////////////////////////////////
//  DomainRepository.java
//  Macromedia ActionScript Implementation of the Interface DomainRepository
//  Generated by Enterprise Architect
//  Created on:      02-May-2021 6:19:47 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.DomainModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 02-May-2021 6:19:47 AM
 */
public interface DomainRepository extends JpaRepository<DomainModel,Integer>, RepositoryExt<DomainModel> {

	/**
	 * 
	 * @param htmltagId
	 */
	public List<DomainModel> findByHtmltagId(int htmltagId);

}