///////////////////////////////////////////////////////////
//  ModuleRepository.java
//  Macromedia ActionScript Implementation of the Interface ModuleRepository
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:05:20 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.ModuleModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:05:20 AM
 */
public interface ModuleRepository extends JpaRepository<ModuleModel,Integer>, RepositoryExt<ModuleModel> {

	/**
	 * 
	 * @param componentId
	 */
	public List<ModuleModel> findByComponentId(int componentId);

	/**
	 * 
	 * @param htmltagId
	 */
	public List<ModuleModel> findByHtmltagId(int htmltagId);

}