///////////////////////////////////////////////////////////
//  PersonRepository.java
//  Macromedia ActionScript Implementation of the Interface PersonRepository
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2021 12:02:44 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.PersonModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Mar-2021 12:02:44 AM
 */
public interface PersonRepository extends JpaRepository<PersonModel,Integer>, RepositoryExt<PersonModel> {

	/**
	 * 
	 * @param languageId
	 */
	public List<PersonModel> findByLanguageId(int languageId);

	/**
	 * 
	 * @param personstatusId
	 */
	public List<PersonModel> findByPersonstatusId(int personstatusId);

	/**
	 * 
	 * @param tenantId
	 */
	public List<PersonModel> findByTenantId(int tenantId);

}