///////////////////////////////////////////////////////////
//  PreferenceRepository.java
//  Macromedia ActionScript Implementation of the Interface PreferenceRepository
//  Generated by Enterprise Architect
//  Created on:      27-Jul-2020 8:43:06 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.PreferenceModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 27-Jul-2020 8:43:06 AM
 */
public interface PreferenceRepository extends JpaRepository<PreferenceModel,Integer>, RepositoryExt<PreferenceModel> {

	/**
	 * 
	 * @param alertId
	 */
	public List<PreferenceModel> findByAlertId(int alertId);

	/**
	 * 
	 * @param stylethemeId
	 */
	public List<PreferenceModel> findByStylethemeId(int stylethemeId);

	/**
	 * 
	 * @param userId
	 */
	public List<PreferenceModel> findByUserId(int userId);

}