///////////////////////////////////////////////////////////
//  ProjectRepository.java
//  Macromedia ActionScript Implementation of the Interface ProjectRepository
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:03 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.util.RepositoryExt;
import java.util.List;
import org.ebs.model.ProjectModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:03 PM
 */
public interface ProjectRepository extends JpaRepository<ProjectModel,Integer>, RepositoryExt<ProjectModel> {

	/**
	 * 
	 * @param personId
	 */
	public List<ProjectModel> findByPersonId(int personId);

	/**
	 * 
	 * @param pipelineId
	 */
	public List<ProjectModel> findByPipelineId(int pipelineId);

	/**
	 * 
	 * @param programId
	 */
	public List<ProjectModel> findByProgramId(int programId);

}