///////////////////////////////////////////////////////////
//  ServiceProviderRepository.java
//  Macromedia ActionScript Implementation of the Interface ServiceProviderRepository
//  Generated by Enterprise Architect
//  Created on:      07-Sep-2020 8:12:07 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.ServiceProviderModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Sep-2020 8:12:07 AM
 */
public interface ServiceProviderRepository extends JpaRepository<ServiceProviderModel,Integer>, RepositoryExt<ServiceProviderModel> {

	/**
	 * 
	 * @param countryId
	 */
	public List<ServiceProviderModel> findByCountryId(int countryId);

}