///////////////////////////////////////////////////////////
//  TraitClassRepository.java
//  Macromedia ActionScript Implementation of the Interface TraitClassRepository
//  Generated by Enterprise Architect
//  Created on:      17-May-2020 3:10:27 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.util.RepositoryExt;
import java.util.List;
import org.ebs.model.TraitClassModel;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 17-May-2020 3:10:27 PM
 */
public interface TraitClassRepository extends JpaRepository<TraitClassModel,Integer>, RepositoryExt<TraitClassModel> {

}