///////////////////////////////////////////////////////////
//  TranslationRepository.java
//  Macromedia ActionScript Implementation of the Interface TranslationRepository
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 10:06:22 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.TranslationModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 04-Sep-2020 10:06:22 AM
 */
public interface TranslationRepository extends JpaRepository<TranslationModel,Integer>, RepositoryExt<TranslationModel> {

	/**
	 * 
	 * @param htmltagId
	 */
	public List<TranslationModel> findByHtmltagId(int htmltagId);

	/**
	 * 
	 * @param languageId
	 */
	public List<TranslationModel> findByLanguageId(int languageId);

}