///////////////////////////////////////////////////////////
//  VendorRepository.java
//  Macromedia ActionScript Implementation of the Interface VendorRepository
//  Generated by Enterprise Architect
//  Created on:      09-Aug-2020 4:51:50 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.VendorModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 09-Aug-2020 4:51:50 PM
 */
public interface VendorRepository extends JpaRepository<VendorModel,Integer>, RepositoryExt<VendorModel> {

	/**
	 * 
	 * @param dataformatId
	 */
	public List<VendorModel> findByDataformatId(int dataformatId);

	/**
	 * 
	 * @param personId
	 */
	public List<VendorModel> findByPersonId(int personId);

	/**
	 * 
	 * @param technologyplatformId
	 */
	public List<VendorModel> findByTechnologyplatformId(int technologyplatformId);

}