///////////////////////////////////////////////////////////
//  WorkflowStatusTypeRepository.java
//  Macromedia ActionScript Implementation of the Interface WorkflowStatusTypeRepository
//  Generated by Enterprise Architect
//  Created on:      07-Aug-2020 3:03:01 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.WorkflowStatusTypeModel;
import org.ebs.util.RepositoryExt;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 07-Aug-2020 3:03:01 PM
 */
public interface WorkflowStatusTypeRepository extends JpaRepository<WorkflowStatusTypeModel,Integer>, RepositoryExt<WorkflowStatusTypeModel> {

}