///////////////////////////////////////////////////////////
//  WorkflowEventRepository.java
//  Macromedia ActionScript Implementation of the Interface WorkflowEventRepository
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:14:53 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.WorkflowEventModel;
import org.ebs.util.RepositoryExt;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:14:53 PM
 */
public interface WorkflowEventRepository extends JpaRepository<WorkflowEventModel,Integer>, RepositoryExt<WorkflowEventModel> {

}