///////////////////////////////////////////////////////////
//  WorkflowNodeCFRepository.java
//  Macromedia ActionScript Implementation of the Interface WorkflowNodeCFRepository
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2020 5:14:57 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.WorkflowNodeCFModel;
import org.ebs.util.RepositoryExt;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 15-Jun-2020 5:14:57 PM
 */
public interface WorkflowNodeCFRepository extends JpaRepository<WorkflowNodeCFModel,Integer>, RepositoryExt<WorkflowNodeCFModel> {

}