///////////////////////////////////////////////////////////
//  WorkflowStatusRepository.java
//  Macromedia ActionScript Implementation of the Interface WorkflowStatusRepository
//  Generated by Enterprise Architect
//  Created on:      10-Sep-2020 12:21:00 AM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.WorkflowStatusModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 10-Sep-2020 12:21:00 AM
 */
public interface WorkflowStatusRepository extends JpaRepository<WorkflowStatusModel,Integer>, RepositoryExt<WorkflowStatusModel> {

	/**
	 * 
	 * @param workflowinstanceId
	 */
	public List<WorkflowStatusModel> findByWorkflowinstanceId(int workflowinstanceId);

	/**
	 * 
	 * @param workflowstatustypeId
	 */
	public List<WorkflowStatusModel> findByWorkflowstatustypeId(int workflowstatustypeId);

}