///////////////////////////////////////////////////////////
//  WorkflowRepository.java
//  Macromedia ActionScript Implementation of the Interface WorkflowRepository
//  Generated by Enterprise Architect
//  Created on:      13-Jul-2020 5:07:50 PM
//  Original author: EBRIONES
///////////////////////////////////////////////////////////

package org.ebs.model.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.ebs.model.WorkflowModel;
import org.ebs.util.RepositoryExt;
import java.util.List;

/**
 * @author EBRIONES
 * @version 1.0
 * @created 13-Jul-2020 5:07:50 PM
 */
public interface WorkflowRepository extends JpaRepository<WorkflowModel,Integer>, RepositoryExt<WorkflowModel> {

	/**
	 * 
	 * @param tenantId
	 */
	public List<WorkflowModel> findByTenantId(int tenantId);

	/**
	 * 
	 * @param workflownodeId
	 */
	public List<WorkflowModel> findByWorkflownodeId(int workflownodeId);

}