[server]
hostname = "localhost"
serverUrl= "https://${carbon.local.ip}:${carbon.management.port}${carbon.context}/services/"

[keystore.tls]
file_name = "wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

[mediation]
synapse.enable_xpath_dom_failover="true"

[management_api.cors]
enabled = false

[management_api.authorization_handler]
enable = false

[synapse_properties]
'synapse.rest.CORSConfig.enabled' = "true"
'synapse.rest.CORSConfig.Access-Control-Allow-Origin' = "*"
'synapse.rest.CORSConfig.Access-Control-Allow-Headers' = "content-type"

[[transport.mail.sender]]
name = "mailto"
parameter.hostname = "$env{spring_email_hostname}"
parameter.port = "$env{spring_email_port}"
parameter.enable_tls = $env{spring_email_enable_tls}
parameter.auth = $env{spring_email_auth}
parameter.username = "$env{spring_email_username}"
parameter.password = "$env{spring_email_password}"
parameter.from = "$env{spring_email_from}"

[transport.local.sender.nonblocking]
enable = true

[transport.rabbitmq.sender]
enable=true

[transport.rabbitmq.listener]
enable=true
name = "AMQPConnectionFactory"
hostname = "172.18.4.42"
port = 5672
username = "guest"
password = "guest"


